// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: proto/course_service.proto

package courseservicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Course struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AccessType    string                 `protobuf:"bytes,4,opt,name=access_type,json=accessType,proto3" json:"access_type,omitempty"`
	IsPublished   bool                   `protobuf:"varint,5,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	OwnerId       string                 `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_proto_course_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_proto_course_service_proto_rawDescGZIP(), []int{0}
}

func (x *Course) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Course) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Course) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Course) GetAccessType() string {
	if x != nil {
		return x.AccessType
	}
	return ""
}

func (x *Course) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *Course) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type CreateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AccessType    string                 `protobuf:"bytes,3,opt,name=access_type,json=accessType,proto3" json:"access_type,omitempty"`
	OwnerId       string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseRequest) Reset() {
	*x = CreateCourseRequest{}
	mi := &file_proto_course_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseRequest) ProtoMessage() {}

func (x *CreateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseRequest) Descriptor() ([]byte, []int) {
	return file_proto_course_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCourseRequest) GetAccessType() string {
	if x != nil {
		return x.AccessType
	}
	return ""
}

func (x *CreateCourseRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type CreateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseResponse) Reset() {
	*x = CreateCourseResponse{}
	mi := &file_proto_course_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseResponse) ProtoMessage() {}

func (x *CreateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseResponse.ProtoReflect.Descriptor instead.
func (*CreateCourseResponse) Descriptor() ([]byte, []int) {
	return file_proto_course_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

type ReadCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCourseRequest) Reset() {
	*x = ReadCourseRequest{}
	mi := &file_proto_course_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCourseRequest) ProtoMessage() {}

func (x *ReadCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCourseRequest.ProtoReflect.Descriptor instead.
func (*ReadCourseRequest) Descriptor() ([]byte, []int) {
	return file_proto_course_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReadCourseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCourseResponse) Reset() {
	*x = ReadCourseResponse{}
	mi := &file_proto_course_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCourseResponse) ProtoMessage() {}

func (x *ReadCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCourseResponse.ProtoReflect.Descriptor instead.
func (*ReadCourseResponse) Descriptor() ([]byte, []int) {
	return file_proto_course_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReadCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

type ReadAllCoursesByOwnerIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllCoursesByOwnerIdRequest) Reset() {
	*x = ReadAllCoursesByOwnerIdRequest{}
	mi := &file_proto_course_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCoursesByOwnerIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCoursesByOwnerIdRequest) ProtoMessage() {}

func (x *ReadAllCoursesByOwnerIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCoursesByOwnerIdRequest.ProtoReflect.Descriptor instead.
func (*ReadAllCoursesByOwnerIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_course_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReadAllCoursesByOwnerIdRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type ReadAllCoursesByOwnerIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*Course              `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllCoursesByOwnerIdResponse) Reset() {
	*x = ReadAllCoursesByOwnerIdResponse{}
	mi := &file_proto_course_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCoursesByOwnerIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCoursesByOwnerIdResponse) ProtoMessage() {}

func (x *ReadAllCoursesByOwnerIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCoursesByOwnerIdResponse.ProtoReflect.Descriptor instead.
func (*ReadAllCoursesByOwnerIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_course_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReadAllCoursesByOwnerIdResponse) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

type ReadAllCoursesByGroupIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupIds      []string               `protobuf:"bytes,1,rep,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllCoursesByGroupIdsRequest) Reset() {
	*x = ReadAllCoursesByGroupIdsRequest{}
	mi := &file_proto_course_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCoursesByGroupIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCoursesByGroupIdsRequest) ProtoMessage() {}

func (x *ReadAllCoursesByGroupIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCoursesByGroupIdsRequest.ProtoReflect.Descriptor instead.
func (*ReadAllCoursesByGroupIdsRequest) Descriptor() ([]byte, []int) {
	return file_proto_course_service_proto_rawDescGZIP(), []int{7}
}

func (x *ReadAllCoursesByGroupIdsRequest) GetGroupIds() []string {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

type ReadAllCoursesByGroupIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*Course              `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllCoursesByGroupIdsResponse) Reset() {
	*x = ReadAllCoursesByGroupIdsResponse{}
	mi := &file_proto_course_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCoursesByGroupIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCoursesByGroupIdsResponse) ProtoMessage() {}

func (x *ReadAllCoursesByGroupIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCoursesByGroupIdsResponse.ProtoReflect.Descriptor instead.
func (*ReadAllCoursesByGroupIdsResponse) Descriptor() ([]byte, []int) {
	return file_proto_course_service_proto_rawDescGZIP(), []int{8}
}

func (x *ReadAllCoursesByGroupIdsResponse) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

type UpdateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AccessType    string                 `protobuf:"bytes,4,opt,name=access_type,json=accessType,proto3" json:"access_type,omitempty"`
	IsPublished   bool                   `protobuf:"varint,5,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseRequest) Reset() {
	*x = UpdateCourseRequest{}
	mi := &file_proto_course_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseRequest) ProtoMessage() {}

func (x *UpdateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseRequest.ProtoReflect.Descriptor instead.
func (*UpdateCourseRequest) Descriptor() ([]byte, []int) {
	return file_proto_course_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCourseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateCourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCourseRequest) GetAccessType() string {
	if x != nil {
		return x.AccessType
	}
	return ""
}

func (x *UpdateCourseRequest) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

type UpdateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseResponse) Reset() {
	*x = UpdateCourseResponse{}
	mi := &file_proto_course_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseResponse) ProtoMessage() {}

func (x *UpdateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseResponse.ProtoReflect.Descriptor instead.
func (*UpdateCourseResponse) Descriptor() ([]byte, []int) {
	return file_proto_course_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

type DeleteCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseRequest) Reset() {
	*x = DeleteCourseRequest{}
	mi := &file_proto_course_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseRequest) ProtoMessage() {}

func (x *DeleteCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourseRequest) Descriptor() ([]byte, []int) {
	return file_proto_course_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteCourseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseResponse) Reset() {
	*x = DeleteCourseResponse{}
	mi := &file_proto_course_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseResponse) ProtoMessage() {}

func (x *DeleteCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseResponse.ProtoReflect.Descriptor instead.
func (*DeleteCourseResponse) Descriptor() ([]byte, []int) {
	return file_proto_course_service_proto_rawDescGZIP(), []int{12}
}

var File_proto_course_service_proto protoreflect.FileDescriptor

const file_proto_course_service_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/course_service.proto\x12\rcourseservice\"\xaf\x01\n" +
	"\x06Course\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vaccess_type\x18\x04 \x01(\tR\n" +
	"accessType\x12!\n" +
	"\fis_published\x18\x05 \x01(\bR\visPublished\x12\x19\n" +
	"\bowner_id\x18\x06 \x01(\tR\aownerId\"\x89\x01\n" +
	"\x13CreateCourseRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vaccess_type\x18\x03 \x01(\tR\n" +
	"accessType\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\"E\n" +
	"\x14CreateCourseResponse\x12-\n" +
	"\x06course\x18\x01 \x01(\v2\x15.courseservice.CourseR\x06course\"#\n" +
	"\x11ReadCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x12ReadCourseResponse\x12-\n" +
	"\x06course\x18\x01 \x01(\v2\x15.courseservice.CourseR\x06course\";\n" +
	"\x1eReadAllCoursesByOwnerIdRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\"R\n" +
	"\x1fReadAllCoursesByOwnerIdResponse\x12/\n" +
	"\acourses\x18\x01 \x03(\v2\x15.courseservice.CourseR\acourses\">\n" +
	"\x1fReadAllCoursesByGroupIdsRequest\x12\x1b\n" +
	"\tgroup_ids\x18\x01 \x03(\tR\bgroupIds\"S\n" +
	" ReadAllCoursesByGroupIdsResponse\x12/\n" +
	"\acourses\x18\x01 \x03(\v2\x15.courseservice.CourseR\acourses\"\xa1\x01\n" +
	"\x13UpdateCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vaccess_type\x18\x04 \x01(\tR\n" +
	"accessType\x12!\n" +
	"\fis_published\x18\x05 \x01(\bR\visPublished\"E\n" +
	"\x14UpdateCourseResponse\x12-\n" +
	"\x06course\x18\x01 \x01(\v2\x15.courseservice.CourseR\x06course\"%\n" +
	"\x13DeleteCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteCourseResponse2\xe4\x04\n" +
	"\rCourseService\x12W\n" +
	"\fCreateCourse\x12\".courseservice.CreateCourseRequest\x1a#.courseservice.CreateCourseResponse\x12Q\n" +
	"\n" +
	"ReadCourse\x12 .courseservice.ReadCourseRequest\x1a!.courseservice.ReadCourseResponse\x12x\n" +
	"\x17ReadAllCoursesByOwnerId\x12-.courseservice.ReadAllCoursesByOwnerIdRequest\x1a..courseservice.ReadAllCoursesByOwnerIdResponse\x12{\n" +
	"\x18ReadAllCoursesByGroupIds\x12..courseservice.ReadAllCoursesByGroupIdsRequest\x1a/.courseservice.ReadAllCoursesByGroupIdsResponse\x12W\n" +
	"\fUpdateCourse\x12\".courseservice.UpdateCourseRequest\x1a#.courseservice.UpdateCourseResponse\x12W\n" +
	"\fDeleteCourse\x12\".courseservice.DeleteCourseRequest\x1a#.courseservice.DeleteCourseResponseB\x17Z\x15proto/courseservicepbb\x06proto3"

var (
	file_proto_course_service_proto_rawDescOnce sync.Once
	file_proto_course_service_proto_rawDescData []byte
)

func file_proto_course_service_proto_rawDescGZIP() []byte {
	file_proto_course_service_proto_rawDescOnce.Do(func() {
		file_proto_course_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_course_service_proto_rawDesc), len(file_proto_course_service_proto_rawDesc)))
	})
	return file_proto_course_service_proto_rawDescData
}

var file_proto_course_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_course_service_proto_goTypes = []any{
	(*Course)(nil),                           // 0: courseservice.Course
	(*CreateCourseRequest)(nil),              // 1: courseservice.CreateCourseRequest
	(*CreateCourseResponse)(nil),             // 2: courseservice.CreateCourseResponse
	(*ReadCourseRequest)(nil),                // 3: courseservice.ReadCourseRequest
	(*ReadCourseResponse)(nil),               // 4: courseservice.ReadCourseResponse
	(*ReadAllCoursesByOwnerIdRequest)(nil),   // 5: courseservice.ReadAllCoursesByOwnerIdRequest
	(*ReadAllCoursesByOwnerIdResponse)(nil),  // 6: courseservice.ReadAllCoursesByOwnerIdResponse
	(*ReadAllCoursesByGroupIdsRequest)(nil),  // 7: courseservice.ReadAllCoursesByGroupIdsRequest
	(*ReadAllCoursesByGroupIdsResponse)(nil), // 8: courseservice.ReadAllCoursesByGroupIdsResponse
	(*UpdateCourseRequest)(nil),              // 9: courseservice.UpdateCourseRequest
	(*UpdateCourseResponse)(nil),             // 10: courseservice.UpdateCourseResponse
	(*DeleteCourseRequest)(nil),              // 11: courseservice.DeleteCourseRequest
	(*DeleteCourseResponse)(nil),             // 12: courseservice.DeleteCourseResponse
}
var file_proto_course_service_proto_depIdxs = []int32{
	0,  // 0: courseservice.CreateCourseResponse.course:type_name -> courseservice.Course
	0,  // 1: courseservice.ReadCourseResponse.course:type_name -> courseservice.Course
	0,  // 2: courseservice.ReadAllCoursesByOwnerIdResponse.courses:type_name -> courseservice.Course
	0,  // 3: courseservice.ReadAllCoursesByGroupIdsResponse.courses:type_name -> courseservice.Course
	0,  // 4: courseservice.UpdateCourseResponse.course:type_name -> courseservice.Course
	1,  // 5: courseservice.CourseService.CreateCourse:input_type -> courseservice.CreateCourseRequest
	3,  // 6: courseservice.CourseService.ReadCourse:input_type -> courseservice.ReadCourseRequest
	5,  // 7: courseservice.CourseService.ReadAllCoursesByOwnerId:input_type -> courseservice.ReadAllCoursesByOwnerIdRequest
	7,  // 8: courseservice.CourseService.ReadAllCoursesByGroupIds:input_type -> courseservice.ReadAllCoursesByGroupIdsRequest
	9,  // 9: courseservice.CourseService.UpdateCourse:input_type -> courseservice.UpdateCourseRequest
	11, // 10: courseservice.CourseService.DeleteCourse:input_type -> courseservice.DeleteCourseRequest
	2,  // 11: courseservice.CourseService.CreateCourse:output_type -> courseservice.CreateCourseResponse
	4,  // 12: courseservice.CourseService.ReadCourse:output_type -> courseservice.ReadCourseResponse
	6,  // 13: courseservice.CourseService.ReadAllCoursesByOwnerId:output_type -> courseservice.ReadAllCoursesByOwnerIdResponse
	8,  // 14: courseservice.CourseService.ReadAllCoursesByGroupIds:output_type -> courseservice.ReadAllCoursesByGroupIdsResponse
	10, // 15: courseservice.CourseService.UpdateCourse:output_type -> courseservice.UpdateCourseResponse
	12, // 16: courseservice.CourseService.DeleteCourse:output_type -> courseservice.DeleteCourseResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_course_service_proto_init() }
func file_proto_course_service_proto_init() {
	if File_proto_course_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_course_service_proto_rawDesc), len(file_proto_course_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_course_service_proto_goTypes,
		DependencyIndexes: file_proto_course_service_proto_depIdxs,
		MessageInfos:      file_proto_course_service_proto_msgTypes,
	}.Build()
	File_proto_course_service_proto = out.File
	file_proto_course_service_proto_goTypes = nil
	file_proto_course_service_proto_depIdxs = nil
}
