// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/task_service.proto

package taskservicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType int32

const (
	TaskType_TASK_TYPE_UNSPECIFIED TaskType = 0
	TaskType_TASK_TYPE_TEXT_INPUT  TaskType = 1
	TaskType_TASK_TYPE_CHOICE      TaskType = 2
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNSPECIFIED",
		1: "TASK_TYPE_TEXT_INPUT",
		2: "TASK_TYPE_CHOICE",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNSPECIFIED": 0,
		"TASK_TYPE_TEXT_INPUT":  1,
		"TASK_TYPE_CHOICE":      2,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_task_service_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_proto_task_service_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{0}
}

type TaskOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	IsCorrect     bool                   `protobuf:"varint,3,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskOption) Reset() {
	*x = TaskOption{}
	mi := &file_proto_task_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOption) ProtoMessage() {}

func (x *TaskOption) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOption.ProtoReflect.Descriptor instead.
func (*TaskOption) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{0}
}

func (x *TaskOption) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskOption) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TaskOption) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

type Task struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CourseId          string                 `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	ModuleId          string                 `protobuf:"bytes,4,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	Type              TaskType               `protobuf:"varint,5,opt,name=type,proto3,enum=taskservice.TaskType" json:"type,omitempty"`
	CorrectTextAnswer string                 `protobuf:"bytes,6,opt,name=correct_text_answer,json=correctTextAnswer,proto3" json:"correct_text_answer,omitempty"`
	Options           []*TaskOption          `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_task_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Task) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *Task) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *Task) GetCorrectTextAnswer() string {
	if x != nil {
		return x.CorrectTextAnswer
	}
	return ""
}

func (x *Task) GetOptions() []*TaskOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type CreateTaskRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Title             string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	CourseId          string                 `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	ModuleId          string                 `protobuf:"bytes,4,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	Type              TaskType               `protobuf:"varint,5,opt,name=type,proto3,enum=taskservice.TaskType" json:"type,omitempty"`
	CorrectTextAnswer string                 `protobuf:"bytes,6,opt,name=correct_text_answer,json=correctTextAnswer,proto3" json:"correct_text_answer,omitempty"`
	Options           []*TaskOption          `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_proto_task_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CreateTaskRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *CreateTaskRequest) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *CreateTaskRequest) GetCorrectTextAnswer() string {
	if x != nil {
		return x.CorrectTextAnswer
	}
	return ""
}

func (x *CreateTaskRequest) GetOptions() []*TaskOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_proto_task_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ReadTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTaskRequest) Reset() {
	*x = ReadTaskRequest{}
	mi := &file_proto_task_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTaskRequest) ProtoMessage() {}

func (x *ReadTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTaskRequest.ProtoReflect.Descriptor instead.
func (*ReadTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReadTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTaskResponse) Reset() {
	*x = ReadTaskResponse{}
	mi := &file_proto_task_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTaskResponse) ProtoMessage() {}

func (x *ReadTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTaskResponse.ProtoReflect.Descriptor instead.
func (*ReadTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReadTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ReadAllTasksByCourseIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllTasksByCourseIdRequest) Reset() {
	*x = ReadAllTasksByCourseIdRequest{}
	mi := &file_proto_task_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllTasksByCourseIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllTasksByCourseIdRequest) ProtoMessage() {}

func (x *ReadAllTasksByCourseIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllTasksByCourseIdRequest.ProtoReflect.Descriptor instead.
func (*ReadAllTasksByCourseIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReadAllTasksByCourseIdRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type ReadAllTasksByCourseIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllTasksByCourseIdResponse) Reset() {
	*x = ReadAllTasksByCourseIdResponse{}
	mi := &file_proto_task_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllTasksByCourseIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllTasksByCourseIdResponse) ProtoMessage() {}

func (x *ReadAllTasksByCourseIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllTasksByCourseIdResponse.ProtoReflect.Descriptor instead.
func (*ReadAllTasksByCourseIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{7}
}

func (x *ReadAllTasksByCourseIdResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ReadAllTasksByModuleIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllTasksByModuleIdRequest) Reset() {
	*x = ReadAllTasksByModuleIdRequest{}
	mi := &file_proto_task_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllTasksByModuleIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllTasksByModuleIdRequest) ProtoMessage() {}

func (x *ReadAllTasksByModuleIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllTasksByModuleIdRequest.ProtoReflect.Descriptor instead.
func (*ReadAllTasksByModuleIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{8}
}

func (x *ReadAllTasksByModuleIdRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

type ReadAllTasksByModuleIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllTasksByModuleIdResponse) Reset() {
	*x = ReadAllTasksByModuleIdResponse{}
	mi := &file_proto_task_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllTasksByModuleIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllTasksByModuleIdResponse) ProtoMessage() {}

func (x *ReadAllTasksByModuleIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllTasksByModuleIdResponse.ProtoReflect.Descriptor instead.
func (*ReadAllTasksByModuleIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{9}
}

func (x *ReadAllTasksByModuleIdResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type UpdateTaskRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CourseId          string                 `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	ModuleId          string                 `protobuf:"bytes,4,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	Type              TaskType               `protobuf:"varint,5,opt,name=type,proto3,enum=taskservice.TaskType" json:"type,omitempty"`
	CorrectTextAnswer string                 `protobuf:"bytes,6,opt,name=correct_text_answer,json=correctTextAnswer,proto3" json:"correct_text_answer,omitempty"`
	Options           []*TaskOption          `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_proto_task_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTaskRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *UpdateTaskRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *UpdateTaskRequest) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *UpdateTaskRequest) GetCorrectTextAnswer() string {
	if x != nil {
		return x.CorrectTextAnswer
	}
	return ""
}

func (x *UpdateTaskRequest) GetOptions() []*TaskOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type UpdateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskResponse) Reset() {
	*x = UpdateTaskResponse{}
	mi := &file_proto_task_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResponse) ProtoMessage() {}

func (x *UpdateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_proto_task_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_proto_task_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{13}
}

var File_proto_task_service_proto protoreflect.FileDescriptor

const file_proto_task_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/task_service.proto\x12\vtaskservice\"O\n" +
	"\n" +
	"TaskOption\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x03 \x01(\bR\tisCorrect\"\xf4\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\tR\bcourseId\x12\x1b\n" +
	"\tmodule_id\x18\x04 \x01(\tR\bmoduleId\x12)\n" +
	"\x04type\x18\x05 \x01(\x0e2\x15.taskservice.TaskTypeR\x04type\x12.\n" +
	"\x13correct_text_answer\x18\x06 \x01(\tR\x11correctTextAnswer\x121\n" +
	"\aoptions\x18\a \x03(\v2\x17.taskservice.TaskOptionR\aoptions\"\xf1\x01\n" +
	"\x11CreateTaskRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\tR\bcourseId\x12\x1b\n" +
	"\tmodule_id\x18\x04 \x01(\tR\bmoduleId\x12)\n" +
	"\x04type\x18\x05 \x01(\x0e2\x15.taskservice.TaskTypeR\x04type\x12.\n" +
	"\x13correct_text_answer\x18\x06 \x01(\tR\x11correctTextAnswer\x121\n" +
	"\aoptions\x18\a \x03(\v2\x17.taskservice.TaskOptionR\aoptions\";\n" +
	"\x12CreateTaskResponse\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.taskservice.TaskR\x04task\"!\n" +
	"\x0fReadTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x10ReadTaskResponse\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.taskservice.TaskR\x04task\"<\n" +
	"\x1dReadAllTasksByCourseIdRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"I\n" +
	"\x1eReadAllTasksByCourseIdResponse\x12'\n" +
	"\x05tasks\x18\x01 \x03(\v2\x11.taskservice.TaskR\x05tasks\"<\n" +
	"\x1dReadAllTasksByModuleIdRequest\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\"I\n" +
	"\x1eReadAllTasksByModuleIdResponse\x12'\n" +
	"\x05tasks\x18\x01 \x03(\v2\x11.taskservice.TaskR\x05tasks\"\x81\x02\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\tR\bcourseId\x12\x1b\n" +
	"\tmodule_id\x18\x04 \x01(\tR\bmoduleId\x12)\n" +
	"\x04type\x18\x05 \x01(\x0e2\x15.taskservice.TaskTypeR\x04type\x12.\n" +
	"\x13correct_text_answer\x18\x06 \x01(\tR\x11correctTextAnswer\x121\n" +
	"\aoptions\x18\a \x03(\v2\x17.taskservice.TaskOptionR\aoptions\";\n" +
	"\x12UpdateTaskResponse\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.taskservice.TaskR\x04task\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteTaskResponse*U\n" +
	"\bTaskType\x12\x19\n" +
	"\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TASK_TYPE_TEXT_INPUT\x10\x01\x12\x14\n" +
	"\x10TASK_TYPE_CHOICE\x10\x022\xa9\x04\n" +
	"\vTaskService\x12M\n" +
	"\n" +
	"CreateTask\x12\x1e.taskservice.CreateTaskRequest\x1a\x1f.taskservice.CreateTaskResponse\x12G\n" +
	"\bReadTask\x12\x1c.taskservice.ReadTaskRequest\x1a\x1d.taskservice.ReadTaskResponse\x12q\n" +
	"\x16ReadAllTasksByCourseId\x12*.taskservice.ReadAllTasksByCourseIdRequest\x1a+.taskservice.ReadAllTasksByCourseIdResponse\x12q\n" +
	"\x16ReadAllTasksByModuleId\x12*.taskservice.ReadAllTasksByModuleIdRequest\x1a+.taskservice.ReadAllTasksByModuleIdResponse\x12M\n" +
	"\n" +
	"UpdateTask\x12\x1e.taskservice.UpdateTaskRequest\x1a\x1f.taskservice.UpdateTaskResponse\x12M\n" +
	"\n" +
	"DeleteTask\x12\x1e.taskservice.DeleteTaskRequest\x1a\x1f.taskservice.DeleteTaskResponseB\x15Z\x13proto/taskservicepbb\x06proto3"

var (
	file_proto_task_service_proto_rawDescOnce sync.Once
	file_proto_task_service_proto_rawDescData []byte
)

func file_proto_task_service_proto_rawDescGZIP() []byte {
	file_proto_task_service_proto_rawDescOnce.Do(func() {
		file_proto_task_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_task_service_proto_rawDesc), len(file_proto_task_service_proto_rawDesc)))
	})
	return file_proto_task_service_proto_rawDescData
}

var file_proto_task_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_task_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_task_service_proto_goTypes = []any{
	(TaskType)(0),                          // 0: taskservice.TaskType
	(*TaskOption)(nil),                     // 1: taskservice.TaskOption
	(*Task)(nil),                           // 2: taskservice.Task
	(*CreateTaskRequest)(nil),              // 3: taskservice.CreateTaskRequest
	(*CreateTaskResponse)(nil),             // 4: taskservice.CreateTaskResponse
	(*ReadTaskRequest)(nil),                // 5: taskservice.ReadTaskRequest
	(*ReadTaskResponse)(nil),               // 6: taskservice.ReadTaskResponse
	(*ReadAllTasksByCourseIdRequest)(nil),  // 7: taskservice.ReadAllTasksByCourseIdRequest
	(*ReadAllTasksByCourseIdResponse)(nil), // 8: taskservice.ReadAllTasksByCourseIdResponse
	(*ReadAllTasksByModuleIdRequest)(nil),  // 9: taskservice.ReadAllTasksByModuleIdRequest
	(*ReadAllTasksByModuleIdResponse)(nil), // 10: taskservice.ReadAllTasksByModuleIdResponse
	(*UpdateTaskRequest)(nil),              // 11: taskservice.UpdateTaskRequest
	(*UpdateTaskResponse)(nil),             // 12: taskservice.UpdateTaskResponse
	(*DeleteTaskRequest)(nil),              // 13: taskservice.DeleteTaskRequest
	(*DeleteTaskResponse)(nil),             // 14: taskservice.DeleteTaskResponse
}
var file_proto_task_service_proto_depIdxs = []int32{
	0,  // 0: taskservice.Task.type:type_name -> taskservice.TaskType
	1,  // 1: taskservice.Task.options:type_name -> taskservice.TaskOption
	0,  // 2: taskservice.CreateTaskRequest.type:type_name -> taskservice.TaskType
	1,  // 3: taskservice.CreateTaskRequest.options:type_name -> taskservice.TaskOption
	2,  // 4: taskservice.CreateTaskResponse.task:type_name -> taskservice.Task
	2,  // 5: taskservice.ReadTaskResponse.task:type_name -> taskservice.Task
	2,  // 6: taskservice.ReadAllTasksByCourseIdResponse.tasks:type_name -> taskservice.Task
	2,  // 7: taskservice.ReadAllTasksByModuleIdResponse.tasks:type_name -> taskservice.Task
	0,  // 8: taskservice.UpdateTaskRequest.type:type_name -> taskservice.TaskType
	1,  // 9: taskservice.UpdateTaskRequest.options:type_name -> taskservice.TaskOption
	2,  // 10: taskservice.UpdateTaskResponse.task:type_name -> taskservice.Task
	3,  // 11: taskservice.TaskService.CreateTask:input_type -> taskservice.CreateTaskRequest
	5,  // 12: taskservice.TaskService.ReadTask:input_type -> taskservice.ReadTaskRequest
	7,  // 13: taskservice.TaskService.ReadAllTasksByCourseId:input_type -> taskservice.ReadAllTasksByCourseIdRequest
	9,  // 14: taskservice.TaskService.ReadAllTasksByModuleId:input_type -> taskservice.ReadAllTasksByModuleIdRequest
	11, // 15: taskservice.TaskService.UpdateTask:input_type -> taskservice.UpdateTaskRequest
	13, // 16: taskservice.TaskService.DeleteTask:input_type -> taskservice.DeleteTaskRequest
	4,  // 17: taskservice.TaskService.CreateTask:output_type -> taskservice.CreateTaskResponse
	6,  // 18: taskservice.TaskService.ReadTask:output_type -> taskservice.ReadTaskResponse
	8,  // 19: taskservice.TaskService.ReadAllTasksByCourseId:output_type -> taskservice.ReadAllTasksByCourseIdResponse
	10, // 20: taskservice.TaskService.ReadAllTasksByModuleId:output_type -> taskservice.ReadAllTasksByModuleIdResponse
	12, // 21: taskservice.TaskService.UpdateTask:output_type -> taskservice.UpdateTaskResponse
	14, // 22: taskservice.TaskService.DeleteTask:output_type -> taskservice.DeleteTaskResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_task_service_proto_init() }
func file_proto_task_service_proto_init() {
	if File_proto_task_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_task_service_proto_rawDesc), len(file_proto_task_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_task_service_proto_goTypes,
		DependencyIndexes: file_proto_task_service_proto_depIdxs,
		EnumInfos:         file_proto_task_service_proto_enumTypes,
		MessageInfos:      file_proto_task_service_proto_msgTypes,
	}.Build()
	File_proto_task_service_proto = out.File
	file_proto_task_service_proto_goTypes = nil
	file_proto_task_service_proto_depIdxs = nil
}
