// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: proto/task_attempt_service.proto

package taskattemptservicepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskAttemptService_SubmitTaskAttempt_FullMethodName                      = "/taskattemptservice.TaskAttemptService/SubmitTaskAttempt"
	TaskAttemptService_ReadTaskAttempt_FullMethodName                        = "/taskattemptservice.TaskAttemptService/ReadTaskAttempt"
	TaskAttemptService_ReadAllTaskAttemptsByUserIdAndModuleId_FullMethodName = "/taskattemptservice.TaskAttemptService/ReadAllTaskAttemptsByUserIdAndModuleId"
	TaskAttemptService_ReadAllTaskAttemptsByUserIdAndCourseId_FullMethodName = "/taskattemptservice.TaskAttemptService/ReadAllTaskAttemptsByUserIdAndCourseId"
	TaskAttemptService_ReadAllTaskAttemptsByCourseId_FullMethodName          = "/taskattemptservice.TaskAttemptService/ReadAllTaskAttemptsByCourseId"
	TaskAttemptService_ReadAllTaskAttemptsByModuleId_FullMethodName          = "/taskattemptservice.TaskAttemptService/ReadAllTaskAttemptsByModuleId"
)

// TaskAttemptServiceClient is the client API for TaskAttemptService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskAttemptServiceClient interface {
	SubmitTaskAttempt(ctx context.Context, in *SubmitTaskAttemptRequest, opts ...grpc.CallOption) (*SubmitTaskAttemptResponse, error)
	ReadTaskAttempt(ctx context.Context, in *ReadTaskAttemptRequest, opts ...grpc.CallOption) (*ReadTaskAttemptResponse, error)
	ReadAllTaskAttemptsByUserIdAndModuleId(ctx context.Context, in *ReadAllTaskAttemptsByUserIdAndModuleIdRequest, opts ...grpc.CallOption) (*ReadAllTaskAttemptsByUserIdAndModuleIdResponse, error)
	ReadAllTaskAttemptsByUserIdAndCourseId(ctx context.Context, in *ReadAllTaskAttemptsByUserIdAndCourseIdRequest, opts ...grpc.CallOption) (*ReadAllTaskAttemptsByUserIdAndCourseIdResponse, error)
	ReadAllTaskAttemptsByCourseId(ctx context.Context, in *ReadAllTaskAttemptsByCourseIdRequest, opts ...grpc.CallOption) (*ReadAllTaskAttemptsByCourseIdResponse, error)
	ReadAllTaskAttemptsByModuleId(ctx context.Context, in *ReadAllTaskAttemptsByModuleIdRequest, opts ...grpc.CallOption) (*ReadAllTaskAttemptsByModuleIdResponse, error)
}

type taskAttemptServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskAttemptServiceClient(cc grpc.ClientConnInterface) TaskAttemptServiceClient {
	return &taskAttemptServiceClient{cc}
}

func (c *taskAttemptServiceClient) SubmitTaskAttempt(ctx context.Context, in *SubmitTaskAttemptRequest, opts ...grpc.CallOption) (*SubmitTaskAttemptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitTaskAttemptResponse)
	err := c.cc.Invoke(ctx, TaskAttemptService_SubmitTaskAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskAttemptServiceClient) ReadTaskAttempt(ctx context.Context, in *ReadTaskAttemptRequest, opts ...grpc.CallOption) (*ReadTaskAttemptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadTaskAttemptResponse)
	err := c.cc.Invoke(ctx, TaskAttemptService_ReadTaskAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskAttemptServiceClient) ReadAllTaskAttemptsByUserIdAndModuleId(ctx context.Context, in *ReadAllTaskAttemptsByUserIdAndModuleIdRequest, opts ...grpc.CallOption) (*ReadAllTaskAttemptsByUserIdAndModuleIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadAllTaskAttemptsByUserIdAndModuleIdResponse)
	err := c.cc.Invoke(ctx, TaskAttemptService_ReadAllTaskAttemptsByUserIdAndModuleId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskAttemptServiceClient) ReadAllTaskAttemptsByUserIdAndCourseId(ctx context.Context, in *ReadAllTaskAttemptsByUserIdAndCourseIdRequest, opts ...grpc.CallOption) (*ReadAllTaskAttemptsByUserIdAndCourseIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadAllTaskAttemptsByUserIdAndCourseIdResponse)
	err := c.cc.Invoke(ctx, TaskAttemptService_ReadAllTaskAttemptsByUserIdAndCourseId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskAttemptServiceClient) ReadAllTaskAttemptsByCourseId(ctx context.Context, in *ReadAllTaskAttemptsByCourseIdRequest, opts ...grpc.CallOption) (*ReadAllTaskAttemptsByCourseIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadAllTaskAttemptsByCourseIdResponse)
	err := c.cc.Invoke(ctx, TaskAttemptService_ReadAllTaskAttemptsByCourseId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskAttemptServiceClient) ReadAllTaskAttemptsByModuleId(ctx context.Context, in *ReadAllTaskAttemptsByModuleIdRequest, opts ...grpc.CallOption) (*ReadAllTaskAttemptsByModuleIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadAllTaskAttemptsByModuleIdResponse)
	err := c.cc.Invoke(ctx, TaskAttemptService_ReadAllTaskAttemptsByModuleId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskAttemptServiceServer is the server API for TaskAttemptService service.
// All implementations must embed UnimplementedTaskAttemptServiceServer
// for forward compatibility.
type TaskAttemptServiceServer interface {
	SubmitTaskAttempt(context.Context, *SubmitTaskAttemptRequest) (*SubmitTaskAttemptResponse, error)
	ReadTaskAttempt(context.Context, *ReadTaskAttemptRequest) (*ReadTaskAttemptResponse, error)
	ReadAllTaskAttemptsByUserIdAndModuleId(context.Context, *ReadAllTaskAttemptsByUserIdAndModuleIdRequest) (*ReadAllTaskAttemptsByUserIdAndModuleIdResponse, error)
	ReadAllTaskAttemptsByUserIdAndCourseId(context.Context, *ReadAllTaskAttemptsByUserIdAndCourseIdRequest) (*ReadAllTaskAttemptsByUserIdAndCourseIdResponse, error)
	ReadAllTaskAttemptsByCourseId(context.Context, *ReadAllTaskAttemptsByCourseIdRequest) (*ReadAllTaskAttemptsByCourseIdResponse, error)
	ReadAllTaskAttemptsByModuleId(context.Context, *ReadAllTaskAttemptsByModuleIdRequest) (*ReadAllTaskAttemptsByModuleIdResponse, error)
	mustEmbedUnimplementedTaskAttemptServiceServer()
}

// UnimplementedTaskAttemptServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskAttemptServiceServer struct{}

func (UnimplementedTaskAttemptServiceServer) SubmitTaskAttempt(context.Context, *SubmitTaskAttemptRequest) (*SubmitTaskAttemptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTaskAttempt not implemented")
}
func (UnimplementedTaskAttemptServiceServer) ReadTaskAttempt(context.Context, *ReadTaskAttemptRequest) (*ReadTaskAttemptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadTaskAttempt not implemented")
}
func (UnimplementedTaskAttemptServiceServer) ReadAllTaskAttemptsByUserIdAndModuleId(context.Context, *ReadAllTaskAttemptsByUserIdAndModuleIdRequest) (*ReadAllTaskAttemptsByUserIdAndModuleIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadAllTaskAttemptsByUserIdAndModuleId not implemented")
}
func (UnimplementedTaskAttemptServiceServer) ReadAllTaskAttemptsByUserIdAndCourseId(context.Context, *ReadAllTaskAttemptsByUserIdAndCourseIdRequest) (*ReadAllTaskAttemptsByUserIdAndCourseIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadAllTaskAttemptsByUserIdAndCourseId not implemented")
}
func (UnimplementedTaskAttemptServiceServer) ReadAllTaskAttemptsByCourseId(context.Context, *ReadAllTaskAttemptsByCourseIdRequest) (*ReadAllTaskAttemptsByCourseIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadAllTaskAttemptsByCourseId not implemented")
}
func (UnimplementedTaskAttemptServiceServer) ReadAllTaskAttemptsByModuleId(context.Context, *ReadAllTaskAttemptsByModuleIdRequest) (*ReadAllTaskAttemptsByModuleIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadAllTaskAttemptsByModuleId not implemented")
}
func (UnimplementedTaskAttemptServiceServer) mustEmbedUnimplementedTaskAttemptServiceServer() {}
func (UnimplementedTaskAttemptServiceServer) testEmbeddedByValue()                            {}

// UnsafeTaskAttemptServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskAttemptServiceServer will
// result in compilation errors.
type UnsafeTaskAttemptServiceServer interface {
	mustEmbedUnimplementedTaskAttemptServiceServer()
}

func RegisterTaskAttemptServiceServer(s grpc.ServiceRegistrar, srv TaskAttemptServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskAttemptServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskAttemptService_ServiceDesc, srv)
}

func _TaskAttemptService_SubmitTaskAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTaskAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskAttemptServiceServer).SubmitTaskAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskAttemptService_SubmitTaskAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskAttemptServiceServer).SubmitTaskAttempt(ctx, req.(*SubmitTaskAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskAttemptService_ReadTaskAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadTaskAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskAttemptServiceServer).ReadTaskAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskAttemptService_ReadTaskAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskAttemptServiceServer).ReadTaskAttempt(ctx, req.(*ReadTaskAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskAttemptService_ReadAllTaskAttemptsByUserIdAndModuleId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllTaskAttemptsByUserIdAndModuleIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskAttemptServiceServer).ReadAllTaskAttemptsByUserIdAndModuleId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskAttemptService_ReadAllTaskAttemptsByUserIdAndModuleId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskAttemptServiceServer).ReadAllTaskAttemptsByUserIdAndModuleId(ctx, req.(*ReadAllTaskAttemptsByUserIdAndModuleIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskAttemptService_ReadAllTaskAttemptsByUserIdAndCourseId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllTaskAttemptsByUserIdAndCourseIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskAttemptServiceServer).ReadAllTaskAttemptsByUserIdAndCourseId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskAttemptService_ReadAllTaskAttemptsByUserIdAndCourseId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskAttemptServiceServer).ReadAllTaskAttemptsByUserIdAndCourseId(ctx, req.(*ReadAllTaskAttemptsByUserIdAndCourseIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskAttemptService_ReadAllTaskAttemptsByCourseId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllTaskAttemptsByCourseIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskAttemptServiceServer).ReadAllTaskAttemptsByCourseId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskAttemptService_ReadAllTaskAttemptsByCourseId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskAttemptServiceServer).ReadAllTaskAttemptsByCourseId(ctx, req.(*ReadAllTaskAttemptsByCourseIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskAttemptService_ReadAllTaskAttemptsByModuleId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllTaskAttemptsByModuleIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskAttemptServiceServer).ReadAllTaskAttemptsByModuleId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskAttemptService_ReadAllTaskAttemptsByModuleId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskAttemptServiceServer).ReadAllTaskAttemptsByModuleId(ctx, req.(*ReadAllTaskAttemptsByModuleIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskAttemptService_ServiceDesc is the grpc.ServiceDesc for TaskAttemptService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskAttemptService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taskattemptservice.TaskAttemptService",
	HandlerType: (*TaskAttemptServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTaskAttempt",
			Handler:    _TaskAttemptService_SubmitTaskAttempt_Handler,
		},
		{
			MethodName: "ReadTaskAttempt",
			Handler:    _TaskAttemptService_ReadTaskAttempt_Handler,
		},
		{
			MethodName: "ReadAllTaskAttemptsByUserIdAndModuleId",
			Handler:    _TaskAttemptService_ReadAllTaskAttemptsByUserIdAndModuleId_Handler,
		},
		{
			MethodName: "ReadAllTaskAttemptsByUserIdAndCourseId",
			Handler:    _TaskAttemptService_ReadAllTaskAttemptsByUserIdAndCourseId_Handler,
		},
		{
			MethodName: "ReadAllTaskAttemptsByCourseId",
			Handler:    _TaskAttemptService_ReadAllTaskAttemptsByCourseId_Handler,
		},
		{
			MethodName: "ReadAllTaskAttemptsByModuleId",
			Handler:    _TaskAttemptService_ReadAllTaskAttemptsByModuleId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/task_attempt_service.proto",
}
