// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/task_attempt_service.proto

package taskattemptservicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskAttemptAnswer struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TaskId            string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TextAnswer        string                 `protobuf:"bytes,2,opt,name=text_answer,json=textAnswer,proto3" json:"text_answer,omitempty"`
	SelectedOptionIds []string               `protobuf:"bytes,3,rep,name=selected_option_ids,json=selectedOptionIds,proto3" json:"selected_option_ids,omitempty"`
	IsCorrect         bool                   `protobuf:"varint,4,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskAttemptAnswer) Reset() {
	*x = TaskAttemptAnswer{}
	mi := &file_proto_task_attempt_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAttemptAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAttemptAnswer) ProtoMessage() {}

func (x *TaskAttemptAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_attempt_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAttemptAnswer.ProtoReflect.Descriptor instead.
func (*TaskAttemptAnswer) Descriptor() ([]byte, []int) {
	return file_proto_task_attempt_service_proto_rawDescGZIP(), []int{0}
}

func (x *TaskAttemptAnswer) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAttemptAnswer) GetTextAnswer() string {
	if x != nil {
		return x.TextAnswer
	}
	return ""
}

func (x *TaskAttemptAnswer) GetSelectedOptionIds() []string {
	if x != nil {
		return x.SelectedOptionIds
	}
	return nil
}

func (x *TaskAttemptAnswer) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

type TaskAttempt struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId       string                 `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	ModuleId       string                 `protobuf:"bytes,4,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	AttemptNumber  int64                  `protobuf:"varint,5,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	Answers        []*TaskAttemptAnswer   `protobuf:"bytes,6,rep,name=answers,proto3" json:"answers,omitempty"`
	CorrectAnswers int64                  `protobuf:"varint,7,opt,name=correct_answers,json=correctAnswers,proto3" json:"correct_answers,omitempty"`
	TotalQuestions int64                  `protobuf:"varint,8,opt,name=total_questions,json=totalQuestions,proto3" json:"total_questions,omitempty"`
	Score          float64                `protobuf:"fixed64,9,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskAttempt) Reset() {
	*x = TaskAttempt{}
	mi := &file_proto_task_attempt_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAttempt) ProtoMessage() {}

func (x *TaskAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_attempt_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAttempt.ProtoReflect.Descriptor instead.
func (*TaskAttempt) Descriptor() ([]byte, []int) {
	return file_proto_task_attempt_service_proto_rawDescGZIP(), []int{1}
}

func (x *TaskAttempt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskAttempt) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TaskAttempt) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *TaskAttempt) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *TaskAttempt) GetAttemptNumber() int64 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *TaskAttempt) GetAnswers() []*TaskAttemptAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *TaskAttempt) GetCorrectAnswers() int64 {
	if x != nil {
		return x.CorrectAnswers
	}
	return 0
}

func (x *TaskAttempt) GetTotalQuestions() int64 {
	if x != nil {
		return x.TotalQuestions
	}
	return 0
}

func (x *TaskAttempt) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SubmitTaskAttemptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	ModuleId      string                 `protobuf:"bytes,3,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	Answers       []*TaskAttemptAnswer   `protobuf:"bytes,4,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskAttemptRequest) Reset() {
	*x = SubmitTaskAttemptRequest{}
	mi := &file_proto_task_attempt_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskAttemptRequest) ProtoMessage() {}

func (x *SubmitTaskAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_attempt_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskAttemptRequest.ProtoReflect.Descriptor instead.
func (*SubmitTaskAttemptRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_attempt_service_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitTaskAttemptRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitTaskAttemptRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *SubmitTaskAttemptRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *SubmitTaskAttemptRequest) GetAnswers() []*TaskAttemptAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

type SubmitTaskAttemptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskAttempt   *TaskAttempt           `protobuf:"bytes,1,opt,name=task_attempt,json=taskAttempt,proto3" json:"task_attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskAttemptResponse) Reset() {
	*x = SubmitTaskAttemptResponse{}
	mi := &file_proto_task_attempt_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskAttemptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskAttemptResponse) ProtoMessage() {}

func (x *SubmitTaskAttemptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_attempt_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskAttemptResponse.ProtoReflect.Descriptor instead.
func (*SubmitTaskAttemptResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_attempt_service_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitTaskAttemptResponse) GetTaskAttempt() *TaskAttempt {
	if x != nil {
		return x.TaskAttempt
	}
	return nil
}

type ReadTaskAttemptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTaskAttemptRequest) Reset() {
	*x = ReadTaskAttemptRequest{}
	mi := &file_proto_task_attempt_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTaskAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTaskAttemptRequest) ProtoMessage() {}

func (x *ReadTaskAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_attempt_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTaskAttemptRequest.ProtoReflect.Descriptor instead.
func (*ReadTaskAttemptRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_attempt_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReadTaskAttemptRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadTaskAttemptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskAttempt   *TaskAttempt           `protobuf:"bytes,1,opt,name=task_attempt,json=taskAttempt,proto3" json:"task_attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTaskAttemptResponse) Reset() {
	*x = ReadTaskAttemptResponse{}
	mi := &file_proto_task_attempt_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTaskAttemptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTaskAttemptResponse) ProtoMessage() {}

func (x *ReadTaskAttemptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_attempt_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTaskAttemptResponse.ProtoReflect.Descriptor instead.
func (*ReadTaskAttemptResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_attempt_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReadTaskAttemptResponse) GetTaskAttempt() *TaskAttempt {
	if x != nil {
		return x.TaskAttempt
	}
	return nil
}

type ReadAllTaskAttemptsByUserIdAndModuleIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ModuleId      string                 `protobuf:"bytes,2,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllTaskAttemptsByUserIdAndModuleIdRequest) Reset() {
	*x = ReadAllTaskAttemptsByUserIdAndModuleIdRequest{}
	mi := &file_proto_task_attempt_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllTaskAttemptsByUserIdAndModuleIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllTaskAttemptsByUserIdAndModuleIdRequest) ProtoMessage() {}

func (x *ReadAllTaskAttemptsByUserIdAndModuleIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_attempt_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllTaskAttemptsByUserIdAndModuleIdRequest.ProtoReflect.Descriptor instead.
func (*ReadAllTaskAttemptsByUserIdAndModuleIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_attempt_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReadAllTaskAttemptsByUserIdAndModuleIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReadAllTaskAttemptsByUserIdAndModuleIdRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

type ReadAllTaskAttemptsByUserIdAndModuleIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskAttempts  []*TaskAttempt         `protobuf:"bytes,1,rep,name=task_attempts,json=taskAttempts,proto3" json:"task_attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllTaskAttemptsByUserIdAndModuleIdResponse) Reset() {
	*x = ReadAllTaskAttemptsByUserIdAndModuleIdResponse{}
	mi := &file_proto_task_attempt_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllTaskAttemptsByUserIdAndModuleIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllTaskAttemptsByUserIdAndModuleIdResponse) ProtoMessage() {}

func (x *ReadAllTaskAttemptsByUserIdAndModuleIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_attempt_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllTaskAttemptsByUserIdAndModuleIdResponse.ProtoReflect.Descriptor instead.
func (*ReadAllTaskAttemptsByUserIdAndModuleIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_attempt_service_proto_rawDescGZIP(), []int{7}
}

func (x *ReadAllTaskAttemptsByUserIdAndModuleIdResponse) GetTaskAttempts() []*TaskAttempt {
	if x != nil {
		return x.TaskAttempts
	}
	return nil
}

type ReadAllTaskAttemptsByUserIdAndCourseIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllTaskAttemptsByUserIdAndCourseIdRequest) Reset() {
	*x = ReadAllTaskAttemptsByUserIdAndCourseIdRequest{}
	mi := &file_proto_task_attempt_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllTaskAttemptsByUserIdAndCourseIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllTaskAttemptsByUserIdAndCourseIdRequest) ProtoMessage() {}

func (x *ReadAllTaskAttemptsByUserIdAndCourseIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_attempt_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllTaskAttemptsByUserIdAndCourseIdRequest.ProtoReflect.Descriptor instead.
func (*ReadAllTaskAttemptsByUserIdAndCourseIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_attempt_service_proto_rawDescGZIP(), []int{8}
}

func (x *ReadAllTaskAttemptsByUserIdAndCourseIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReadAllTaskAttemptsByUserIdAndCourseIdRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type ReadAllTaskAttemptsByUserIdAndCourseIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskAttempts  []*TaskAttempt         `protobuf:"bytes,1,rep,name=task_attempts,json=taskAttempts,proto3" json:"task_attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllTaskAttemptsByUserIdAndCourseIdResponse) Reset() {
	*x = ReadAllTaskAttemptsByUserIdAndCourseIdResponse{}
	mi := &file_proto_task_attempt_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllTaskAttemptsByUserIdAndCourseIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllTaskAttemptsByUserIdAndCourseIdResponse) ProtoMessage() {}

func (x *ReadAllTaskAttemptsByUserIdAndCourseIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_attempt_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllTaskAttemptsByUserIdAndCourseIdResponse.ProtoReflect.Descriptor instead.
func (*ReadAllTaskAttemptsByUserIdAndCourseIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_attempt_service_proto_rawDescGZIP(), []int{9}
}

func (x *ReadAllTaskAttemptsByUserIdAndCourseIdResponse) GetTaskAttempts() []*TaskAttempt {
	if x != nil {
		return x.TaskAttempts
	}
	return nil
}

type ReadAllTaskAttemptsByCourseIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllTaskAttemptsByCourseIdRequest) Reset() {
	*x = ReadAllTaskAttemptsByCourseIdRequest{}
	mi := &file_proto_task_attempt_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllTaskAttemptsByCourseIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllTaskAttemptsByCourseIdRequest) ProtoMessage() {}

func (x *ReadAllTaskAttemptsByCourseIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_attempt_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllTaskAttemptsByCourseIdRequest.ProtoReflect.Descriptor instead.
func (*ReadAllTaskAttemptsByCourseIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_attempt_service_proto_rawDescGZIP(), []int{10}
}

func (x *ReadAllTaskAttemptsByCourseIdRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type ReadAllTaskAttemptsByCourseIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskAttempts  []*TaskAttempt         `protobuf:"bytes,1,rep,name=task_attempts,json=taskAttempts,proto3" json:"task_attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllTaskAttemptsByCourseIdResponse) Reset() {
	*x = ReadAllTaskAttemptsByCourseIdResponse{}
	mi := &file_proto_task_attempt_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllTaskAttemptsByCourseIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllTaskAttemptsByCourseIdResponse) ProtoMessage() {}

func (x *ReadAllTaskAttemptsByCourseIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_attempt_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllTaskAttemptsByCourseIdResponse.ProtoReflect.Descriptor instead.
func (*ReadAllTaskAttemptsByCourseIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_attempt_service_proto_rawDescGZIP(), []int{11}
}

func (x *ReadAllTaskAttemptsByCourseIdResponse) GetTaskAttempts() []*TaskAttempt {
	if x != nil {
		return x.TaskAttempts
	}
	return nil
}

type ReadAllTaskAttemptsByModuleIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllTaskAttemptsByModuleIdRequest) Reset() {
	*x = ReadAllTaskAttemptsByModuleIdRequest{}
	mi := &file_proto_task_attempt_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllTaskAttemptsByModuleIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllTaskAttemptsByModuleIdRequest) ProtoMessage() {}

func (x *ReadAllTaskAttemptsByModuleIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_attempt_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllTaskAttemptsByModuleIdRequest.ProtoReflect.Descriptor instead.
func (*ReadAllTaskAttemptsByModuleIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_attempt_service_proto_rawDescGZIP(), []int{12}
}

func (x *ReadAllTaskAttemptsByModuleIdRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

type ReadAllTaskAttemptsByModuleIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskAttempts  []*TaskAttempt         `protobuf:"bytes,1,rep,name=task_attempts,json=taskAttempts,proto3" json:"task_attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllTaskAttemptsByModuleIdResponse) Reset() {
	*x = ReadAllTaskAttemptsByModuleIdResponse{}
	mi := &file_proto_task_attempt_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllTaskAttemptsByModuleIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllTaskAttemptsByModuleIdResponse) ProtoMessage() {}

func (x *ReadAllTaskAttemptsByModuleIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_attempt_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllTaskAttemptsByModuleIdResponse.ProtoReflect.Descriptor instead.
func (*ReadAllTaskAttemptsByModuleIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_attempt_service_proto_rawDescGZIP(), []int{13}
}

func (x *ReadAllTaskAttemptsByModuleIdResponse) GetTaskAttempts() []*TaskAttempt {
	if x != nil {
		return x.TaskAttempts
	}
	return nil
}

var File_proto_task_attempt_service_proto protoreflect.FileDescriptor

const file_proto_task_attempt_service_proto_rawDesc = "" +
	"\n" +
	" proto/task_attempt_service.proto\x12\x12taskattemptservice\"\x9c\x01\n" +
	"\x11TaskAttemptAnswer\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vtext_answer\x18\x02 \x01(\tR\n" +
	"textAnswer\x12.\n" +
	"\x13selected_option_ids\x18\x03 \x03(\tR\x11selectedOptionIds\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x04 \x01(\bR\tisCorrect\"\xc0\x02\n" +
	"\vTaskAttempt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\tR\bcourseId\x12\x1b\n" +
	"\tmodule_id\x18\x04 \x01(\tR\bmoduleId\x12%\n" +
	"\x0eattempt_number\x18\x05 \x01(\x03R\rattemptNumber\x12?\n" +
	"\aanswers\x18\x06 \x03(\v2%.taskattemptservice.TaskAttemptAnswerR\aanswers\x12'\n" +
	"\x0fcorrect_answers\x18\a \x01(\x03R\x0ecorrectAnswers\x12'\n" +
	"\x0ftotal_questions\x18\b \x01(\x03R\x0etotalQuestions\x12\x14\n" +
	"\x05score\x18\t \x01(\x01R\x05score\"\xae\x01\n" +
	"\x18SubmitTaskAttemptRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x1b\n" +
	"\tmodule_id\x18\x03 \x01(\tR\bmoduleId\x12?\n" +
	"\aanswers\x18\x04 \x03(\v2%.taskattemptservice.TaskAttemptAnswerR\aanswers\"_\n" +
	"\x19SubmitTaskAttemptResponse\x12B\n" +
	"\ftask_attempt\x18\x01 \x01(\v2\x1f.taskattemptservice.TaskAttemptR\vtaskAttempt\"(\n" +
	"\x16ReadTaskAttemptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"]\n" +
	"\x17ReadTaskAttemptResponse\x12B\n" +
	"\ftask_attempt\x18\x01 \x01(\v2\x1f.taskattemptservice.TaskAttemptR\vtaskAttempt\"e\n" +
	"-ReadAllTaskAttemptsByUserIdAndModuleIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tmodule_id\x18\x02 \x01(\tR\bmoduleId\"v\n" +
	".ReadAllTaskAttemptsByUserIdAndModuleIdResponse\x12D\n" +
	"\rtask_attempts\x18\x01 \x03(\v2\x1f.taskattemptservice.TaskAttemptR\ftaskAttempts\"e\n" +
	"-ReadAllTaskAttemptsByUserIdAndCourseIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"v\n" +
	".ReadAllTaskAttemptsByUserIdAndCourseIdResponse\x12D\n" +
	"\rtask_attempts\x18\x01 \x03(\v2\x1f.taskattemptservice.TaskAttemptR\ftaskAttempts\"C\n" +
	"$ReadAllTaskAttemptsByCourseIdRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"m\n" +
	"%ReadAllTaskAttemptsByCourseIdResponse\x12D\n" +
	"\rtask_attempts\x18\x01 \x03(\v2\x1f.taskattemptservice.TaskAttemptR\ftaskAttempts\"C\n" +
	"$ReadAllTaskAttemptsByModuleIdRequest\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\"m\n" +
	"%ReadAllTaskAttemptsByModuleIdResponse\x12D\n" +
	"\rtask_attempts\x18\x01 \x03(\v2\x1f.taskattemptservice.TaskAttemptR\ftaskAttempts2\x84\a\n" +
	"\x12TaskAttemptService\x12p\n" +
	"\x11SubmitTaskAttempt\x12,.taskattemptservice.SubmitTaskAttemptRequest\x1a-.taskattemptservice.SubmitTaskAttemptResponse\x12j\n" +
	"\x0fReadTaskAttempt\x12*.taskattemptservice.ReadTaskAttemptRequest\x1a+.taskattemptservice.ReadTaskAttemptResponse\x12\xaf\x01\n" +
	"&ReadAllTaskAttemptsByUserIdAndModuleId\x12A.taskattemptservice.ReadAllTaskAttemptsByUserIdAndModuleIdRequest\x1aB.taskattemptservice.ReadAllTaskAttemptsByUserIdAndModuleIdResponse\x12\xaf\x01\n" +
	"&ReadAllTaskAttemptsByUserIdAndCourseId\x12A.taskattemptservice.ReadAllTaskAttemptsByUserIdAndCourseIdRequest\x1aB.taskattemptservice.ReadAllTaskAttemptsByUserIdAndCourseIdResponse\x12\x94\x01\n" +
	"\x1dReadAllTaskAttemptsByCourseId\x128.taskattemptservice.ReadAllTaskAttemptsByCourseIdRequest\x1a9.taskattemptservice.ReadAllTaskAttemptsByCourseIdResponse\x12\x94\x01\n" +
	"\x1dReadAllTaskAttemptsByModuleId\x128.taskattemptservice.ReadAllTaskAttemptsByModuleIdRequest\x1a9.taskattemptservice.ReadAllTaskAttemptsByModuleIdResponseB\x1cZ\x1aproto/taskattemptservicepbb\x06proto3"

var (
	file_proto_task_attempt_service_proto_rawDescOnce sync.Once
	file_proto_task_attempt_service_proto_rawDescData []byte
)

func file_proto_task_attempt_service_proto_rawDescGZIP() []byte {
	file_proto_task_attempt_service_proto_rawDescOnce.Do(func() {
		file_proto_task_attempt_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_task_attempt_service_proto_rawDesc), len(file_proto_task_attempt_service_proto_rawDesc)))
	})
	return file_proto_task_attempt_service_proto_rawDescData
}

var file_proto_task_attempt_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_task_attempt_service_proto_goTypes = []any{
	(*TaskAttemptAnswer)(nil),                              // 0: taskattemptservice.TaskAttemptAnswer
	(*TaskAttempt)(nil),                                    // 1: taskattemptservice.TaskAttempt
	(*SubmitTaskAttemptRequest)(nil),                       // 2: taskattemptservice.SubmitTaskAttemptRequest
	(*SubmitTaskAttemptResponse)(nil),                      // 3: taskattemptservice.SubmitTaskAttemptResponse
	(*ReadTaskAttemptRequest)(nil),                         // 4: taskattemptservice.ReadTaskAttemptRequest
	(*ReadTaskAttemptResponse)(nil),                        // 5: taskattemptservice.ReadTaskAttemptResponse
	(*ReadAllTaskAttemptsByUserIdAndModuleIdRequest)(nil),  // 6: taskattemptservice.ReadAllTaskAttemptsByUserIdAndModuleIdRequest
	(*ReadAllTaskAttemptsByUserIdAndModuleIdResponse)(nil), // 7: taskattemptservice.ReadAllTaskAttemptsByUserIdAndModuleIdResponse
	(*ReadAllTaskAttemptsByUserIdAndCourseIdRequest)(nil),  // 8: taskattemptservice.ReadAllTaskAttemptsByUserIdAndCourseIdRequest
	(*ReadAllTaskAttemptsByUserIdAndCourseIdResponse)(nil), // 9: taskattemptservice.ReadAllTaskAttemptsByUserIdAndCourseIdResponse
	(*ReadAllTaskAttemptsByCourseIdRequest)(nil),           // 10: taskattemptservice.ReadAllTaskAttemptsByCourseIdRequest
	(*ReadAllTaskAttemptsByCourseIdResponse)(nil),          // 11: taskattemptservice.ReadAllTaskAttemptsByCourseIdResponse
	(*ReadAllTaskAttemptsByModuleIdRequest)(nil),           // 12: taskattemptservice.ReadAllTaskAttemptsByModuleIdRequest
	(*ReadAllTaskAttemptsByModuleIdResponse)(nil),          // 13: taskattemptservice.ReadAllTaskAttemptsByModuleIdResponse
}
var file_proto_task_attempt_service_proto_depIdxs = []int32{
	0,  // 0: taskattemptservice.TaskAttempt.answers:type_name -> taskattemptservice.TaskAttemptAnswer
	0,  // 1: taskattemptservice.SubmitTaskAttemptRequest.answers:type_name -> taskattemptservice.TaskAttemptAnswer
	1,  // 2: taskattemptservice.SubmitTaskAttemptResponse.task_attempt:type_name -> taskattemptservice.TaskAttempt
	1,  // 3: taskattemptservice.ReadTaskAttemptResponse.task_attempt:type_name -> taskattemptservice.TaskAttempt
	1,  // 4: taskattemptservice.ReadAllTaskAttemptsByUserIdAndModuleIdResponse.task_attempts:type_name -> taskattemptservice.TaskAttempt
	1,  // 5: taskattemptservice.ReadAllTaskAttemptsByUserIdAndCourseIdResponse.task_attempts:type_name -> taskattemptservice.TaskAttempt
	1,  // 6: taskattemptservice.ReadAllTaskAttemptsByCourseIdResponse.task_attempts:type_name -> taskattemptservice.TaskAttempt
	1,  // 7: taskattemptservice.ReadAllTaskAttemptsByModuleIdResponse.task_attempts:type_name -> taskattemptservice.TaskAttempt
	2,  // 8: taskattemptservice.TaskAttemptService.SubmitTaskAttempt:input_type -> taskattemptservice.SubmitTaskAttemptRequest
	4,  // 9: taskattemptservice.TaskAttemptService.ReadTaskAttempt:input_type -> taskattemptservice.ReadTaskAttemptRequest
	6,  // 10: taskattemptservice.TaskAttemptService.ReadAllTaskAttemptsByUserIdAndModuleId:input_type -> taskattemptservice.ReadAllTaskAttemptsByUserIdAndModuleIdRequest
	8,  // 11: taskattemptservice.TaskAttemptService.ReadAllTaskAttemptsByUserIdAndCourseId:input_type -> taskattemptservice.ReadAllTaskAttemptsByUserIdAndCourseIdRequest
	10, // 12: taskattemptservice.TaskAttemptService.ReadAllTaskAttemptsByCourseId:input_type -> taskattemptservice.ReadAllTaskAttemptsByCourseIdRequest
	12, // 13: taskattemptservice.TaskAttemptService.ReadAllTaskAttemptsByModuleId:input_type -> taskattemptservice.ReadAllTaskAttemptsByModuleIdRequest
	3,  // 14: taskattemptservice.TaskAttemptService.SubmitTaskAttempt:output_type -> taskattemptservice.SubmitTaskAttemptResponse
	5,  // 15: taskattemptservice.TaskAttemptService.ReadTaskAttempt:output_type -> taskattemptservice.ReadTaskAttemptResponse
	7,  // 16: taskattemptservice.TaskAttemptService.ReadAllTaskAttemptsByUserIdAndModuleId:output_type -> taskattemptservice.ReadAllTaskAttemptsByUserIdAndModuleIdResponse
	9,  // 17: taskattemptservice.TaskAttemptService.ReadAllTaskAttemptsByUserIdAndCourseId:output_type -> taskattemptservice.ReadAllTaskAttemptsByUserIdAndCourseIdResponse
	11, // 18: taskattemptservice.TaskAttemptService.ReadAllTaskAttemptsByCourseId:output_type -> taskattemptservice.ReadAllTaskAttemptsByCourseIdResponse
	13, // 19: taskattemptservice.TaskAttemptService.ReadAllTaskAttemptsByModuleId:output_type -> taskattemptservice.ReadAllTaskAttemptsByModuleIdResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_task_attempt_service_proto_init() }
func file_proto_task_attempt_service_proto_init() {
	if File_proto_task_attempt_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_task_attempt_service_proto_rawDesc), len(file_proto_task_attempt_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_task_attempt_service_proto_goTypes,
		DependencyIndexes: file_proto_task_attempt_service_proto_depIdxs,
		MessageInfos:      file_proto_task_attempt_service_proto_msgTypes,
	}.Build()
	File_proto_task_attempt_service_proto = out.File
	file_proto_task_attempt_service_proto_goTypes = nil
	file_proto_task_attempt_service_proto_depIdxs = nil
}
