// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: proto/completed_theory_course_service.proto

package completedtheorycourseservicepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CompletedTheoryCourseService_CreateCompletedTheoryCourse_FullMethodName                  = "/completedtheorycourseservice.CompletedTheoryCourseService/CreateCompletedTheoryCourse"
	CompletedTheoryCourseService_ReadCompletedTheoryCourseByUserIdAndCourseId_FullMethodName = "/completedtheorycourseservice.CompletedTheoryCourseService/ReadCompletedTheoryCourseByUserIdAndCourseId"
	CompletedTheoryCourseService_ReadAllCompletedTheoryCoursesByCourseId_FullMethodName      = "/completedtheorycourseservice.CompletedTheoryCourseService/ReadAllCompletedTheoryCoursesByCourseId"
	CompletedTheoryCourseService_ReadAllCompletedTheoryCoursesByUserId_FullMethodName        = "/completedtheorycourseservice.CompletedTheoryCourseService/ReadAllCompletedTheoryCoursesByUserId"
)

// CompletedTheoryCourseServiceClient is the client API for CompletedTheoryCourseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompletedTheoryCourseServiceClient interface {
	CreateCompletedTheoryCourse(ctx context.Context, in *CreateCompletedTheoryCourseRequest, opts ...grpc.CallOption) (*CreateCompletedTheoryCourseResponse, error)
	ReadCompletedTheoryCourseByUserIdAndCourseId(ctx context.Context, in *ReadCompletedTheoryCourseByUserIdAndCourseIdRequest, opts ...grpc.CallOption) (*ReadCompletedTheoryCourseByUserIdAndCourseIdResponse, error)
	ReadAllCompletedTheoryCoursesByCourseId(ctx context.Context, in *ReadAllCompletedTheoryCoursesByCourseIdRequest, opts ...grpc.CallOption) (*ReadAllCompletedTheoryCoursesByCourseIdResponse, error)
	ReadAllCompletedTheoryCoursesByUserId(ctx context.Context, in *ReadAllCompletedTheoryCoursesByUserIdRequest, opts ...grpc.CallOption) (*ReadAllCompletedTheoryCoursesByUserIdResponse, error)
}

type completedTheoryCourseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCompletedTheoryCourseServiceClient(cc grpc.ClientConnInterface) CompletedTheoryCourseServiceClient {
	return &completedTheoryCourseServiceClient{cc}
}

func (c *completedTheoryCourseServiceClient) CreateCompletedTheoryCourse(ctx context.Context, in *CreateCompletedTheoryCourseRequest, opts ...grpc.CallOption) (*CreateCompletedTheoryCourseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCompletedTheoryCourseResponse)
	err := c.cc.Invoke(ctx, CompletedTheoryCourseService_CreateCompletedTheoryCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *completedTheoryCourseServiceClient) ReadCompletedTheoryCourseByUserIdAndCourseId(ctx context.Context, in *ReadCompletedTheoryCourseByUserIdAndCourseIdRequest, opts ...grpc.CallOption) (*ReadCompletedTheoryCourseByUserIdAndCourseIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadCompletedTheoryCourseByUserIdAndCourseIdResponse)
	err := c.cc.Invoke(ctx, CompletedTheoryCourseService_ReadCompletedTheoryCourseByUserIdAndCourseId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *completedTheoryCourseServiceClient) ReadAllCompletedTheoryCoursesByCourseId(ctx context.Context, in *ReadAllCompletedTheoryCoursesByCourseIdRequest, opts ...grpc.CallOption) (*ReadAllCompletedTheoryCoursesByCourseIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadAllCompletedTheoryCoursesByCourseIdResponse)
	err := c.cc.Invoke(ctx, CompletedTheoryCourseService_ReadAllCompletedTheoryCoursesByCourseId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *completedTheoryCourseServiceClient) ReadAllCompletedTheoryCoursesByUserId(ctx context.Context, in *ReadAllCompletedTheoryCoursesByUserIdRequest, opts ...grpc.CallOption) (*ReadAllCompletedTheoryCoursesByUserIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadAllCompletedTheoryCoursesByUserIdResponse)
	err := c.cc.Invoke(ctx, CompletedTheoryCourseService_ReadAllCompletedTheoryCoursesByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompletedTheoryCourseServiceServer is the server API for CompletedTheoryCourseService service.
// All implementations must embed UnimplementedCompletedTheoryCourseServiceServer
// for forward compatibility.
type CompletedTheoryCourseServiceServer interface {
	CreateCompletedTheoryCourse(context.Context, *CreateCompletedTheoryCourseRequest) (*CreateCompletedTheoryCourseResponse, error)
	ReadCompletedTheoryCourseByUserIdAndCourseId(context.Context, *ReadCompletedTheoryCourseByUserIdAndCourseIdRequest) (*ReadCompletedTheoryCourseByUserIdAndCourseIdResponse, error)
	ReadAllCompletedTheoryCoursesByCourseId(context.Context, *ReadAllCompletedTheoryCoursesByCourseIdRequest) (*ReadAllCompletedTheoryCoursesByCourseIdResponse, error)
	ReadAllCompletedTheoryCoursesByUserId(context.Context, *ReadAllCompletedTheoryCoursesByUserIdRequest) (*ReadAllCompletedTheoryCoursesByUserIdResponse, error)
	mustEmbedUnimplementedCompletedTheoryCourseServiceServer()
}

// UnimplementedCompletedTheoryCourseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompletedTheoryCourseServiceServer struct{}

func (UnimplementedCompletedTheoryCourseServiceServer) CreateCompletedTheoryCourse(context.Context, *CreateCompletedTheoryCourseRequest) (*CreateCompletedTheoryCourseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCompletedTheoryCourse not implemented")
}
func (UnimplementedCompletedTheoryCourseServiceServer) ReadCompletedTheoryCourseByUserIdAndCourseId(context.Context, *ReadCompletedTheoryCourseByUserIdAndCourseIdRequest) (*ReadCompletedTheoryCourseByUserIdAndCourseIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadCompletedTheoryCourseByUserIdAndCourseId not implemented")
}
func (UnimplementedCompletedTheoryCourseServiceServer) ReadAllCompletedTheoryCoursesByCourseId(context.Context, *ReadAllCompletedTheoryCoursesByCourseIdRequest) (*ReadAllCompletedTheoryCoursesByCourseIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadAllCompletedTheoryCoursesByCourseId not implemented")
}
func (UnimplementedCompletedTheoryCourseServiceServer) ReadAllCompletedTheoryCoursesByUserId(context.Context, *ReadAllCompletedTheoryCoursesByUserIdRequest) (*ReadAllCompletedTheoryCoursesByUserIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadAllCompletedTheoryCoursesByUserId not implemented")
}
func (UnimplementedCompletedTheoryCourseServiceServer) mustEmbedUnimplementedCompletedTheoryCourseServiceServer() {
}
func (UnimplementedCompletedTheoryCourseServiceServer) testEmbeddedByValue() {}

// UnsafeCompletedTheoryCourseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompletedTheoryCourseServiceServer will
// result in compilation errors.
type UnsafeCompletedTheoryCourseServiceServer interface {
	mustEmbedUnimplementedCompletedTheoryCourseServiceServer()
}

func RegisterCompletedTheoryCourseServiceServer(s grpc.ServiceRegistrar, srv CompletedTheoryCourseServiceServer) {
	// If the following call panics, it indicates UnimplementedCompletedTheoryCourseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CompletedTheoryCourseService_ServiceDesc, srv)
}

func _CompletedTheoryCourseService_CreateCompletedTheoryCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompletedTheoryCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompletedTheoryCourseServiceServer).CreateCompletedTheoryCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompletedTheoryCourseService_CreateCompletedTheoryCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompletedTheoryCourseServiceServer).CreateCompletedTheoryCourse(ctx, req.(*CreateCompletedTheoryCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompletedTheoryCourseService_ReadCompletedTheoryCourseByUserIdAndCourseId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadCompletedTheoryCourseByUserIdAndCourseIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompletedTheoryCourseServiceServer).ReadCompletedTheoryCourseByUserIdAndCourseId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompletedTheoryCourseService_ReadCompletedTheoryCourseByUserIdAndCourseId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompletedTheoryCourseServiceServer).ReadCompletedTheoryCourseByUserIdAndCourseId(ctx, req.(*ReadCompletedTheoryCourseByUserIdAndCourseIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompletedTheoryCourseService_ReadAllCompletedTheoryCoursesByCourseId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllCompletedTheoryCoursesByCourseIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompletedTheoryCourseServiceServer).ReadAllCompletedTheoryCoursesByCourseId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompletedTheoryCourseService_ReadAllCompletedTheoryCoursesByCourseId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompletedTheoryCourseServiceServer).ReadAllCompletedTheoryCoursesByCourseId(ctx, req.(*ReadAllCompletedTheoryCoursesByCourseIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompletedTheoryCourseService_ReadAllCompletedTheoryCoursesByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllCompletedTheoryCoursesByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompletedTheoryCourseServiceServer).ReadAllCompletedTheoryCoursesByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompletedTheoryCourseService_ReadAllCompletedTheoryCoursesByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompletedTheoryCourseServiceServer).ReadAllCompletedTheoryCoursesByUserId(ctx, req.(*ReadAllCompletedTheoryCoursesByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CompletedTheoryCourseService_ServiceDesc is the grpc.ServiceDesc for CompletedTheoryCourseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CompletedTheoryCourseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "completedtheorycourseservice.CompletedTheoryCourseService",
	HandlerType: (*CompletedTheoryCourseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCompletedTheoryCourse",
			Handler:    _CompletedTheoryCourseService_CreateCompletedTheoryCourse_Handler,
		},
		{
			MethodName: "ReadCompletedTheoryCourseByUserIdAndCourseId",
			Handler:    _CompletedTheoryCourseService_ReadCompletedTheoryCourseByUserIdAndCourseId_Handler,
		},
		{
			MethodName: "ReadAllCompletedTheoryCoursesByCourseId",
			Handler:    _CompletedTheoryCourseService_ReadAllCompletedTheoryCoursesByCourseId_Handler,
		},
		{
			MethodName: "ReadAllCompletedTheoryCoursesByUserId",
			Handler:    _CompletedTheoryCourseService_ReadAllCompletedTheoryCoursesByUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/completed_theory_course_service.proto",
}
