// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/completed_theory_course_service.proto

package completedtheorycourseservicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompletedTheoryCourse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletedTheoryCourse) Reset() {
	*x = CompletedTheoryCourse{}
	mi := &file_proto_completed_theory_course_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletedTheoryCourse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletedTheoryCourse) ProtoMessage() {}

func (x *CompletedTheoryCourse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_theory_course_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletedTheoryCourse.ProtoReflect.Descriptor instead.
func (*CompletedTheoryCourse) Descriptor() ([]byte, []int) {
	return file_proto_completed_theory_course_service_proto_rawDescGZIP(), []int{0}
}

func (x *CompletedTheoryCourse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CompletedTheoryCourse) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type CreateCompletedTheoryCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompletedTheoryCourseRequest) Reset() {
	*x = CreateCompletedTheoryCourseRequest{}
	mi := &file_proto_completed_theory_course_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompletedTheoryCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompletedTheoryCourseRequest) ProtoMessage() {}

func (x *CreateCompletedTheoryCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_theory_course_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompletedTheoryCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCompletedTheoryCourseRequest) Descriptor() ([]byte, []int) {
	return file_proto_completed_theory_course_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCompletedTheoryCourseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCompletedTheoryCourseRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type CreateCompletedTheoryCourseResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CompletedTheoryCourse *CompletedTheoryCourse `protobuf:"bytes,1,opt,name=completed_theory_course,json=completedTheoryCourse,proto3" json:"completed_theory_course,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateCompletedTheoryCourseResponse) Reset() {
	*x = CreateCompletedTheoryCourseResponse{}
	mi := &file_proto_completed_theory_course_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompletedTheoryCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompletedTheoryCourseResponse) ProtoMessage() {}

func (x *CreateCompletedTheoryCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_theory_course_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompletedTheoryCourseResponse.ProtoReflect.Descriptor instead.
func (*CreateCompletedTheoryCourseResponse) Descriptor() ([]byte, []int) {
	return file_proto_completed_theory_course_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCompletedTheoryCourseResponse) GetCompletedTheoryCourse() *CompletedTheoryCourse {
	if x != nil {
		return x.CompletedTheoryCourse
	}
	return nil
}

type ReadCompletedTheoryCourseByUserIdAndCourseIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCompletedTheoryCourseByUserIdAndCourseIdRequest) Reset() {
	*x = ReadCompletedTheoryCourseByUserIdAndCourseIdRequest{}
	mi := &file_proto_completed_theory_course_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCompletedTheoryCourseByUserIdAndCourseIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCompletedTheoryCourseByUserIdAndCourseIdRequest) ProtoMessage() {}

func (x *ReadCompletedTheoryCourseByUserIdAndCourseIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_theory_course_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCompletedTheoryCourseByUserIdAndCourseIdRequest.ProtoReflect.Descriptor instead.
func (*ReadCompletedTheoryCourseByUserIdAndCourseIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_completed_theory_course_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReadCompletedTheoryCourseByUserIdAndCourseIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReadCompletedTheoryCourseByUserIdAndCourseIdRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type ReadCompletedTheoryCourseByUserIdAndCourseIdResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CompletedTheoryCourse *CompletedTheoryCourse `protobuf:"bytes,1,opt,name=completed_theory_course,json=completedTheoryCourse,proto3" json:"completed_theory_course,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ReadCompletedTheoryCourseByUserIdAndCourseIdResponse) Reset() {
	*x = ReadCompletedTheoryCourseByUserIdAndCourseIdResponse{}
	mi := &file_proto_completed_theory_course_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCompletedTheoryCourseByUserIdAndCourseIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCompletedTheoryCourseByUserIdAndCourseIdResponse) ProtoMessage() {}

func (x *ReadCompletedTheoryCourseByUserIdAndCourseIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_theory_course_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCompletedTheoryCourseByUserIdAndCourseIdResponse.ProtoReflect.Descriptor instead.
func (*ReadCompletedTheoryCourseByUserIdAndCourseIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_completed_theory_course_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReadCompletedTheoryCourseByUserIdAndCourseIdResponse) GetCompletedTheoryCourse() *CompletedTheoryCourse {
	if x != nil {
		return x.CompletedTheoryCourse
	}
	return nil
}

type ReadAllCompletedTheoryCoursesByCourseIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllCompletedTheoryCoursesByCourseIdRequest) Reset() {
	*x = ReadAllCompletedTheoryCoursesByCourseIdRequest{}
	mi := &file_proto_completed_theory_course_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCompletedTheoryCoursesByCourseIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCompletedTheoryCoursesByCourseIdRequest) ProtoMessage() {}

func (x *ReadAllCompletedTheoryCoursesByCourseIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_theory_course_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCompletedTheoryCoursesByCourseIdRequest.ProtoReflect.Descriptor instead.
func (*ReadAllCompletedTheoryCoursesByCourseIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_completed_theory_course_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReadAllCompletedTheoryCoursesByCourseIdRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type ReadAllCompletedTheoryCoursesByCourseIdResponse struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	CompletedTheoryCourses []*CompletedTheoryCourse `protobuf:"bytes,1,rep,name=completed_theory_courses,json=completedTheoryCourses,proto3" json:"completed_theory_courses,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReadAllCompletedTheoryCoursesByCourseIdResponse) Reset() {
	*x = ReadAllCompletedTheoryCoursesByCourseIdResponse{}
	mi := &file_proto_completed_theory_course_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCompletedTheoryCoursesByCourseIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCompletedTheoryCoursesByCourseIdResponse) ProtoMessage() {}

func (x *ReadAllCompletedTheoryCoursesByCourseIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_theory_course_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCompletedTheoryCoursesByCourseIdResponse.ProtoReflect.Descriptor instead.
func (*ReadAllCompletedTheoryCoursesByCourseIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_completed_theory_course_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReadAllCompletedTheoryCoursesByCourseIdResponse) GetCompletedTheoryCourses() []*CompletedTheoryCourse {
	if x != nil {
		return x.CompletedTheoryCourses
	}
	return nil
}

type ReadAllCompletedTheoryCoursesByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllCompletedTheoryCoursesByUserIdRequest) Reset() {
	*x = ReadAllCompletedTheoryCoursesByUserIdRequest{}
	mi := &file_proto_completed_theory_course_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCompletedTheoryCoursesByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCompletedTheoryCoursesByUserIdRequest) ProtoMessage() {}

func (x *ReadAllCompletedTheoryCoursesByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_theory_course_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCompletedTheoryCoursesByUserIdRequest.ProtoReflect.Descriptor instead.
func (*ReadAllCompletedTheoryCoursesByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_completed_theory_course_service_proto_rawDescGZIP(), []int{7}
}

func (x *ReadAllCompletedTheoryCoursesByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ReadAllCompletedTheoryCoursesByUserIdResponse struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	CompletedTheoryCourses []*CompletedTheoryCourse `protobuf:"bytes,1,rep,name=completed_theory_courses,json=completedTheoryCourses,proto3" json:"completed_theory_courses,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReadAllCompletedTheoryCoursesByUserIdResponse) Reset() {
	*x = ReadAllCompletedTheoryCoursesByUserIdResponse{}
	mi := &file_proto_completed_theory_course_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCompletedTheoryCoursesByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCompletedTheoryCoursesByUserIdResponse) ProtoMessage() {}

func (x *ReadAllCompletedTheoryCoursesByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_theory_course_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCompletedTheoryCoursesByUserIdResponse.ProtoReflect.Descriptor instead.
func (*ReadAllCompletedTheoryCoursesByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_completed_theory_course_service_proto_rawDescGZIP(), []int{8}
}

func (x *ReadAllCompletedTheoryCoursesByUserIdResponse) GetCompletedTheoryCourses() []*CompletedTheoryCourse {
	if x != nil {
		return x.CompletedTheoryCourses
	}
	return nil
}

var File_proto_completed_theory_course_service_proto protoreflect.FileDescriptor

const file_proto_completed_theory_course_service_proto_rawDesc = "" +
	"\n" +
	"+proto/completed_theory_course_service.proto\x12\x1ccompletedtheorycourseservice\"M\n" +
	"\x15CompletedTheoryCourse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"Z\n" +
	"\"CreateCompletedTheoryCourseRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"\x92\x01\n" +
	"#CreateCompletedTheoryCourseResponse\x12k\n" +
	"\x17completed_theory_course\x18\x01 \x01(\v23.completedtheorycourseservice.CompletedTheoryCourseR\x15completedTheoryCourse\"k\n" +
	"3ReadCompletedTheoryCourseByUserIdAndCourseIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"\xa3\x01\n" +
	"4ReadCompletedTheoryCourseByUserIdAndCourseIdResponse\x12k\n" +
	"\x17completed_theory_course\x18\x01 \x01(\v23.completedtheorycourseservice.CompletedTheoryCourseR\x15completedTheoryCourse\"M\n" +
	".ReadAllCompletedTheoryCoursesByCourseIdRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"\xa0\x01\n" +
	"/ReadAllCompletedTheoryCoursesByCourseIdResponse\x12m\n" +
	"\x18completed_theory_courses\x18\x01 \x03(\v23.completedtheorycourseservice.CompletedTheoryCourseR\x16completedTheoryCourses\"G\n" +
	",ReadAllCompletedTheoryCoursesByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x9e\x01\n" +
	"-ReadAllCompletedTheoryCoursesByUserIdResponse\x12m\n" +
	"\x18completed_theory_courses\x18\x01 \x03(\v23.completedtheorycourseservice.CompletedTheoryCourseR\x16completedTheoryCourses2\xa7\x06\n" +
	"\x1cCompletedTheoryCourseService\x12\xa2\x01\n" +
	"\x1bCreateCompletedTheoryCourse\x12@.completedtheorycourseservice.CreateCompletedTheoryCourseRequest\x1aA.completedtheorycourseservice.CreateCompletedTheoryCourseResponse\x12\xd5\x01\n" +
	",ReadCompletedTheoryCourseByUserIdAndCourseId\x12Q.completedtheorycourseservice.ReadCompletedTheoryCourseByUserIdAndCourseIdRequest\x1aR.completedtheorycourseservice.ReadCompletedTheoryCourseByUserIdAndCourseIdResponse\x12\xc6\x01\n" +
	"'ReadAllCompletedTheoryCoursesByCourseId\x12L.completedtheorycourseservice.ReadAllCompletedTheoryCoursesByCourseIdRequest\x1aM.completedtheorycourseservice.ReadAllCompletedTheoryCoursesByCourseIdResponse\x12\xc0\x01\n" +
	"%ReadAllCompletedTheoryCoursesByUserId\x12J.completedtheorycourseservice.ReadAllCompletedTheoryCoursesByUserIdRequest\x1aK.completedtheorycourseservice.ReadAllCompletedTheoryCoursesByUserIdResponseB&Z$proto/completedtheorycourseservicepbb\x06proto3"

var (
	file_proto_completed_theory_course_service_proto_rawDescOnce sync.Once
	file_proto_completed_theory_course_service_proto_rawDescData []byte
)

func file_proto_completed_theory_course_service_proto_rawDescGZIP() []byte {
	file_proto_completed_theory_course_service_proto_rawDescOnce.Do(func() {
		file_proto_completed_theory_course_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_completed_theory_course_service_proto_rawDesc), len(file_proto_completed_theory_course_service_proto_rawDesc)))
	})
	return file_proto_completed_theory_course_service_proto_rawDescData
}

var file_proto_completed_theory_course_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_completed_theory_course_service_proto_goTypes = []any{
	(*CompletedTheoryCourse)(nil),                                // 0: completedtheorycourseservice.CompletedTheoryCourse
	(*CreateCompletedTheoryCourseRequest)(nil),                   // 1: completedtheorycourseservice.CreateCompletedTheoryCourseRequest
	(*CreateCompletedTheoryCourseResponse)(nil),                  // 2: completedtheorycourseservice.CreateCompletedTheoryCourseResponse
	(*ReadCompletedTheoryCourseByUserIdAndCourseIdRequest)(nil),  // 3: completedtheorycourseservice.ReadCompletedTheoryCourseByUserIdAndCourseIdRequest
	(*ReadCompletedTheoryCourseByUserIdAndCourseIdResponse)(nil), // 4: completedtheorycourseservice.ReadCompletedTheoryCourseByUserIdAndCourseIdResponse
	(*ReadAllCompletedTheoryCoursesByCourseIdRequest)(nil),       // 5: completedtheorycourseservice.ReadAllCompletedTheoryCoursesByCourseIdRequest
	(*ReadAllCompletedTheoryCoursesByCourseIdResponse)(nil),      // 6: completedtheorycourseservice.ReadAllCompletedTheoryCoursesByCourseIdResponse
	(*ReadAllCompletedTheoryCoursesByUserIdRequest)(nil),         // 7: completedtheorycourseservice.ReadAllCompletedTheoryCoursesByUserIdRequest
	(*ReadAllCompletedTheoryCoursesByUserIdResponse)(nil),        // 8: completedtheorycourseservice.ReadAllCompletedTheoryCoursesByUserIdResponse
}
var file_proto_completed_theory_course_service_proto_depIdxs = []int32{
	0, // 0: completedtheorycourseservice.CreateCompletedTheoryCourseResponse.completed_theory_course:type_name -> completedtheorycourseservice.CompletedTheoryCourse
	0, // 1: completedtheorycourseservice.ReadCompletedTheoryCourseByUserIdAndCourseIdResponse.completed_theory_course:type_name -> completedtheorycourseservice.CompletedTheoryCourse
	0, // 2: completedtheorycourseservice.ReadAllCompletedTheoryCoursesByCourseIdResponse.completed_theory_courses:type_name -> completedtheorycourseservice.CompletedTheoryCourse
	0, // 3: completedtheorycourseservice.ReadAllCompletedTheoryCoursesByUserIdResponse.completed_theory_courses:type_name -> completedtheorycourseservice.CompletedTheoryCourse
	1, // 4: completedtheorycourseservice.CompletedTheoryCourseService.CreateCompletedTheoryCourse:input_type -> completedtheorycourseservice.CreateCompletedTheoryCourseRequest
	3, // 5: completedtheorycourseservice.CompletedTheoryCourseService.ReadCompletedTheoryCourseByUserIdAndCourseId:input_type -> completedtheorycourseservice.ReadCompletedTheoryCourseByUserIdAndCourseIdRequest
	5, // 6: completedtheorycourseservice.CompletedTheoryCourseService.ReadAllCompletedTheoryCoursesByCourseId:input_type -> completedtheorycourseservice.ReadAllCompletedTheoryCoursesByCourseIdRequest
	7, // 7: completedtheorycourseservice.CompletedTheoryCourseService.ReadAllCompletedTheoryCoursesByUserId:input_type -> completedtheorycourseservice.ReadAllCompletedTheoryCoursesByUserIdRequest
	2, // 8: completedtheorycourseservice.CompletedTheoryCourseService.CreateCompletedTheoryCourse:output_type -> completedtheorycourseservice.CreateCompletedTheoryCourseResponse
	4, // 9: completedtheorycourseservice.CompletedTheoryCourseService.ReadCompletedTheoryCourseByUserIdAndCourseId:output_type -> completedtheorycourseservice.ReadCompletedTheoryCourseByUserIdAndCourseIdResponse
	6, // 10: completedtheorycourseservice.CompletedTheoryCourseService.ReadAllCompletedTheoryCoursesByCourseId:output_type -> completedtheorycourseservice.ReadAllCompletedTheoryCoursesByCourseIdResponse
	8, // 11: completedtheorycourseservice.CompletedTheoryCourseService.ReadAllCompletedTheoryCoursesByUserId:output_type -> completedtheorycourseservice.ReadAllCompletedTheoryCoursesByUserIdResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_completed_theory_course_service_proto_init() }
func file_proto_completed_theory_course_service_proto_init() {
	if File_proto_completed_theory_course_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_completed_theory_course_service_proto_rawDesc), len(file_proto_completed_theory_course_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_completed_theory_course_service_proto_goTypes,
		DependencyIndexes: file_proto_completed_theory_course_service_proto_depIdxs,
		MessageInfos:      file_proto_completed_theory_course_service_proto_msgTypes,
	}.Build()
	File_proto_completed_theory_course_service_proto = out.File
	file_proto_completed_theory_course_service_proto_goTypes = nil
	file_proto_completed_theory_course_service_proto_depIdxs = nil
}
