// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/completed_course_service.proto

package completedcourseservicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompletedCourse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletedCourse) Reset() {
	*x = CompletedCourse{}
	mi := &file_proto_completed_course_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletedCourse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletedCourse) ProtoMessage() {}

func (x *CompletedCourse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_course_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletedCourse.ProtoReflect.Descriptor instead.
func (*CompletedCourse) Descriptor() ([]byte, []int) {
	return file_proto_completed_course_service_proto_rawDescGZIP(), []int{0}
}

func (x *CompletedCourse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CompletedCourse) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type CreateCompletedCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompletedCourseRequest) Reset() {
	*x = CreateCompletedCourseRequest{}
	mi := &file_proto_completed_course_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompletedCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompletedCourseRequest) ProtoMessage() {}

func (x *CreateCompletedCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_course_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompletedCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCompletedCourseRequest) Descriptor() ([]byte, []int) {
	return file_proto_completed_course_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCompletedCourseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCompletedCourseRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type CreateCompletedCourseResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CompletedCourse *CompletedCourse       `protobuf:"bytes,1,opt,name=completed_course,json=completedCourse,proto3" json:"completed_course,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateCompletedCourseResponse) Reset() {
	*x = CreateCompletedCourseResponse{}
	mi := &file_proto_completed_course_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompletedCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompletedCourseResponse) ProtoMessage() {}

func (x *CreateCompletedCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_course_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompletedCourseResponse.ProtoReflect.Descriptor instead.
func (*CreateCompletedCourseResponse) Descriptor() ([]byte, []int) {
	return file_proto_completed_course_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCompletedCourseResponse) GetCompletedCourse() *CompletedCourse {
	if x != nil {
		return x.CompletedCourse
	}
	return nil
}

type ReadCompletedCourseByUserIdAndCourseIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCompletedCourseByUserIdAndCourseIdRequest) Reset() {
	*x = ReadCompletedCourseByUserIdAndCourseIdRequest{}
	mi := &file_proto_completed_course_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCompletedCourseByUserIdAndCourseIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCompletedCourseByUserIdAndCourseIdRequest) ProtoMessage() {}

func (x *ReadCompletedCourseByUserIdAndCourseIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_course_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCompletedCourseByUserIdAndCourseIdRequest.ProtoReflect.Descriptor instead.
func (*ReadCompletedCourseByUserIdAndCourseIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_completed_course_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReadCompletedCourseByUserIdAndCourseIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReadCompletedCourseByUserIdAndCourseIdRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type ReadCompletedCourseByUserIdAndCourseIdResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CompletedCourse *CompletedCourse       `protobuf:"bytes,1,opt,name=completed_course,json=completedCourse,proto3" json:"completed_course,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReadCompletedCourseByUserIdAndCourseIdResponse) Reset() {
	*x = ReadCompletedCourseByUserIdAndCourseIdResponse{}
	mi := &file_proto_completed_course_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCompletedCourseByUserIdAndCourseIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCompletedCourseByUserIdAndCourseIdResponse) ProtoMessage() {}

func (x *ReadCompletedCourseByUserIdAndCourseIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_course_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCompletedCourseByUserIdAndCourseIdResponse.ProtoReflect.Descriptor instead.
func (*ReadCompletedCourseByUserIdAndCourseIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_completed_course_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReadCompletedCourseByUserIdAndCourseIdResponse) GetCompletedCourse() *CompletedCourse {
	if x != nil {
		return x.CompletedCourse
	}
	return nil
}

type ReadAllCompletedCoursesByCourseIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllCompletedCoursesByCourseIdRequest) Reset() {
	*x = ReadAllCompletedCoursesByCourseIdRequest{}
	mi := &file_proto_completed_course_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCompletedCoursesByCourseIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCompletedCoursesByCourseIdRequest) ProtoMessage() {}

func (x *ReadAllCompletedCoursesByCourseIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_course_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCompletedCoursesByCourseIdRequest.ProtoReflect.Descriptor instead.
func (*ReadAllCompletedCoursesByCourseIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_completed_course_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReadAllCompletedCoursesByCourseIdRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type ReadAllCompletedCoursesByCourseIdResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CompletedCourses []*CompletedCourse     `protobuf:"bytes,1,rep,name=completed_courses,json=completedCourses,proto3" json:"completed_courses,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReadAllCompletedCoursesByCourseIdResponse) Reset() {
	*x = ReadAllCompletedCoursesByCourseIdResponse{}
	mi := &file_proto_completed_course_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCompletedCoursesByCourseIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCompletedCoursesByCourseIdResponse) ProtoMessage() {}

func (x *ReadAllCompletedCoursesByCourseIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_course_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCompletedCoursesByCourseIdResponse.ProtoReflect.Descriptor instead.
func (*ReadAllCompletedCoursesByCourseIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_completed_course_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReadAllCompletedCoursesByCourseIdResponse) GetCompletedCourses() []*CompletedCourse {
	if x != nil {
		return x.CompletedCourses
	}
	return nil
}

type ReadAllCompletedCoursesByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllCompletedCoursesByUserIdRequest) Reset() {
	*x = ReadAllCompletedCoursesByUserIdRequest{}
	mi := &file_proto_completed_course_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCompletedCoursesByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCompletedCoursesByUserIdRequest) ProtoMessage() {}

func (x *ReadAllCompletedCoursesByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_course_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCompletedCoursesByUserIdRequest.ProtoReflect.Descriptor instead.
func (*ReadAllCompletedCoursesByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_completed_course_service_proto_rawDescGZIP(), []int{7}
}

func (x *ReadAllCompletedCoursesByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ReadAllCompletedCoursesByUserIdResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CompletedCourses []*CompletedCourse     `protobuf:"bytes,1,rep,name=completed_courses,json=completedCourses,proto3" json:"completed_courses,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReadAllCompletedCoursesByUserIdResponse) Reset() {
	*x = ReadAllCompletedCoursesByUserIdResponse{}
	mi := &file_proto_completed_course_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCompletedCoursesByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCompletedCoursesByUserIdResponse) ProtoMessage() {}

func (x *ReadAllCompletedCoursesByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_course_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCompletedCoursesByUserIdResponse.ProtoReflect.Descriptor instead.
func (*ReadAllCompletedCoursesByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_completed_course_service_proto_rawDescGZIP(), []int{8}
}

func (x *ReadAllCompletedCoursesByUserIdResponse) GetCompletedCourses() []*CompletedCourse {
	if x != nil {
		return x.CompletedCourses
	}
	return nil
}

var File_proto_completed_course_service_proto protoreflect.FileDescriptor

const file_proto_completed_course_service_proto_rawDesc = "" +
	"\n" +
	"$proto/completed_course_service.proto\x12\x16completedcourseservice\"G\n" +
	"\x0fCompletedCourse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"T\n" +
	"\x1cCreateCompletedCourseRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"s\n" +
	"\x1dCreateCompletedCourseResponse\x12R\n" +
	"\x10completed_course\x18\x01 \x01(\v2'.completedcourseservice.CompletedCourseR\x0fcompletedCourse\"e\n" +
	"-ReadCompletedCourseByUserIdAndCourseIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"\x84\x01\n" +
	".ReadCompletedCourseByUserIdAndCourseIdResponse\x12R\n" +
	"\x10completed_course\x18\x01 \x01(\v2'.completedcourseservice.CompletedCourseR\x0fcompletedCourse\"G\n" +
	"(ReadAllCompletedCoursesByCourseIdRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"\x81\x01\n" +
	")ReadAllCompletedCoursesByCourseIdResponse\x12T\n" +
	"\x11completed_courses\x18\x01 \x03(\v2'.completedcourseservice.CompletedCourseR\x10completedCourses\"A\n" +
	"&ReadAllCompletedCoursesByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x7f\n" +
	"'ReadAllCompletedCoursesByUserIdResponse\x12T\n" +
	"\x11completed_courses\x18\x01 \x03(\v2'.completedcourseservice.CompletedCourseR\x10completedCourses2\xa9\x05\n" +
	"\x16CompletedCourseService\x12\x84\x01\n" +
	"\x15CreateCompletedCourse\x124.completedcourseservice.CreateCompletedCourseRequest\x1a5.completedcourseservice.CreateCompletedCourseResponse\x12\xb7\x01\n" +
	"&ReadCompletedCourseByUserIdAndCourseId\x12E.completedcourseservice.ReadCompletedCourseByUserIdAndCourseIdRequest\x1aF.completedcourseservice.ReadCompletedCourseByUserIdAndCourseIdResponse\x12\xa8\x01\n" +
	"!ReadAllCompletedCoursesByCourseId\x12@.completedcourseservice.ReadAllCompletedCoursesByCourseIdRequest\x1aA.completedcourseservice.ReadAllCompletedCoursesByCourseIdResponse\x12\xa2\x01\n" +
	"\x1fReadAllCompletedCoursesByUserId\x12>.completedcourseservice.ReadAllCompletedCoursesByUserIdRequest\x1a?.completedcourseservice.ReadAllCompletedCoursesByUserIdResponseB Z\x1eproto/completedcourseservicepbb\x06proto3"

var (
	file_proto_completed_course_service_proto_rawDescOnce sync.Once
	file_proto_completed_course_service_proto_rawDescData []byte
)

func file_proto_completed_course_service_proto_rawDescGZIP() []byte {
	file_proto_completed_course_service_proto_rawDescOnce.Do(func() {
		file_proto_completed_course_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_completed_course_service_proto_rawDesc), len(file_proto_completed_course_service_proto_rawDesc)))
	})
	return file_proto_completed_course_service_proto_rawDescData
}

var file_proto_completed_course_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_completed_course_service_proto_goTypes = []any{
	(*CompletedCourse)(nil),                                // 0: completedcourseservice.CompletedCourse
	(*CreateCompletedCourseRequest)(nil),                   // 1: completedcourseservice.CreateCompletedCourseRequest
	(*CreateCompletedCourseResponse)(nil),                  // 2: completedcourseservice.CreateCompletedCourseResponse
	(*ReadCompletedCourseByUserIdAndCourseIdRequest)(nil),  // 3: completedcourseservice.ReadCompletedCourseByUserIdAndCourseIdRequest
	(*ReadCompletedCourseByUserIdAndCourseIdResponse)(nil), // 4: completedcourseservice.ReadCompletedCourseByUserIdAndCourseIdResponse
	(*ReadAllCompletedCoursesByCourseIdRequest)(nil),       // 5: completedcourseservice.ReadAllCompletedCoursesByCourseIdRequest
	(*ReadAllCompletedCoursesByCourseIdResponse)(nil),      // 6: completedcourseservice.ReadAllCompletedCoursesByCourseIdResponse
	(*ReadAllCompletedCoursesByUserIdRequest)(nil),         // 7: completedcourseservice.ReadAllCompletedCoursesByUserIdRequest
	(*ReadAllCompletedCoursesByUserIdResponse)(nil),        // 8: completedcourseservice.ReadAllCompletedCoursesByUserIdResponse
}
var file_proto_completed_course_service_proto_depIdxs = []int32{
	0, // 0: completedcourseservice.CreateCompletedCourseResponse.completed_course:type_name -> completedcourseservice.CompletedCourse
	0, // 1: completedcourseservice.ReadCompletedCourseByUserIdAndCourseIdResponse.completed_course:type_name -> completedcourseservice.CompletedCourse
	0, // 2: completedcourseservice.ReadAllCompletedCoursesByCourseIdResponse.completed_courses:type_name -> completedcourseservice.CompletedCourse
	0, // 3: completedcourseservice.ReadAllCompletedCoursesByUserIdResponse.completed_courses:type_name -> completedcourseservice.CompletedCourse
	1, // 4: completedcourseservice.CompletedCourseService.CreateCompletedCourse:input_type -> completedcourseservice.CreateCompletedCourseRequest
	3, // 5: completedcourseservice.CompletedCourseService.ReadCompletedCourseByUserIdAndCourseId:input_type -> completedcourseservice.ReadCompletedCourseByUserIdAndCourseIdRequest
	5, // 6: completedcourseservice.CompletedCourseService.ReadAllCompletedCoursesByCourseId:input_type -> completedcourseservice.ReadAllCompletedCoursesByCourseIdRequest
	7, // 7: completedcourseservice.CompletedCourseService.ReadAllCompletedCoursesByUserId:input_type -> completedcourseservice.ReadAllCompletedCoursesByUserIdRequest
	2, // 8: completedcourseservice.CompletedCourseService.CreateCompletedCourse:output_type -> completedcourseservice.CreateCompletedCourseResponse
	4, // 9: completedcourseservice.CompletedCourseService.ReadCompletedCourseByUserIdAndCourseId:output_type -> completedcourseservice.ReadCompletedCourseByUserIdAndCourseIdResponse
	6, // 10: completedcourseservice.CompletedCourseService.ReadAllCompletedCoursesByCourseId:output_type -> completedcourseservice.ReadAllCompletedCoursesByCourseIdResponse
	8, // 11: completedcourseservice.CompletedCourseService.ReadAllCompletedCoursesByUserId:output_type -> completedcourseservice.ReadAllCompletedCoursesByUserIdResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_completed_course_service_proto_init() }
func file_proto_completed_course_service_proto_init() {
	if File_proto_completed_course_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_completed_course_service_proto_rawDesc), len(file_proto_completed_course_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_completed_course_service_proto_goTypes,
		DependencyIndexes: file_proto_completed_course_service_proto_depIdxs,
		MessageInfos:      file_proto_completed_course_service_proto_msgTypes,
	}.Build()
	File_proto_completed_course_service_proto = out.File
	file_proto_completed_course_service_proto_goTypes = nil
	file_proto_completed_course_service_proto_depIdxs = nil
}
