// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: proto/completed_course_service.proto

package completedcourseservicepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CompletedCourseService_CreateCompletedCourse_FullMethodName                  = "/completedcourseservice.CompletedCourseService/CreateCompletedCourse"
	CompletedCourseService_ReadCompletedCourseByUserIdAndCourseId_FullMethodName = "/completedcourseservice.CompletedCourseService/ReadCompletedCourseByUserIdAndCourseId"
	CompletedCourseService_ReadAllCompletedCoursesByCourseId_FullMethodName      = "/completedcourseservice.CompletedCourseService/ReadAllCompletedCoursesByCourseId"
	CompletedCourseService_ReadAllCompletedCoursesByUserId_FullMethodName        = "/completedcourseservice.CompletedCourseService/ReadAllCompletedCoursesByUserId"
)

// CompletedCourseServiceClient is the client API for CompletedCourseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompletedCourseServiceClient interface {
	CreateCompletedCourse(ctx context.Context, in *CreateCompletedCourseRequest, opts ...grpc.CallOption) (*CreateCompletedCourseResponse, error)
	ReadCompletedCourseByUserIdAndCourseId(ctx context.Context, in *ReadCompletedCourseByUserIdAndCourseIdRequest, opts ...grpc.CallOption) (*ReadCompletedCourseByUserIdAndCourseIdResponse, error)
	ReadAllCompletedCoursesByCourseId(ctx context.Context, in *ReadAllCompletedCoursesByCourseIdRequest, opts ...grpc.CallOption) (*ReadAllCompletedCoursesByCourseIdResponse, error)
	ReadAllCompletedCoursesByUserId(ctx context.Context, in *ReadAllCompletedCoursesByUserIdRequest, opts ...grpc.CallOption) (*ReadAllCompletedCoursesByUserIdResponse, error)
}

type completedCourseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCompletedCourseServiceClient(cc grpc.ClientConnInterface) CompletedCourseServiceClient {
	return &completedCourseServiceClient{cc}
}

func (c *completedCourseServiceClient) CreateCompletedCourse(ctx context.Context, in *CreateCompletedCourseRequest, opts ...grpc.CallOption) (*CreateCompletedCourseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCompletedCourseResponse)
	err := c.cc.Invoke(ctx, CompletedCourseService_CreateCompletedCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *completedCourseServiceClient) ReadCompletedCourseByUserIdAndCourseId(ctx context.Context, in *ReadCompletedCourseByUserIdAndCourseIdRequest, opts ...grpc.CallOption) (*ReadCompletedCourseByUserIdAndCourseIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadCompletedCourseByUserIdAndCourseIdResponse)
	err := c.cc.Invoke(ctx, CompletedCourseService_ReadCompletedCourseByUserIdAndCourseId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *completedCourseServiceClient) ReadAllCompletedCoursesByCourseId(ctx context.Context, in *ReadAllCompletedCoursesByCourseIdRequest, opts ...grpc.CallOption) (*ReadAllCompletedCoursesByCourseIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadAllCompletedCoursesByCourseIdResponse)
	err := c.cc.Invoke(ctx, CompletedCourseService_ReadAllCompletedCoursesByCourseId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *completedCourseServiceClient) ReadAllCompletedCoursesByUserId(ctx context.Context, in *ReadAllCompletedCoursesByUserIdRequest, opts ...grpc.CallOption) (*ReadAllCompletedCoursesByUserIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadAllCompletedCoursesByUserIdResponse)
	err := c.cc.Invoke(ctx, CompletedCourseService_ReadAllCompletedCoursesByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompletedCourseServiceServer is the server API for CompletedCourseService service.
// All implementations must embed UnimplementedCompletedCourseServiceServer
// for forward compatibility.
type CompletedCourseServiceServer interface {
	CreateCompletedCourse(context.Context, *CreateCompletedCourseRequest) (*CreateCompletedCourseResponse, error)
	ReadCompletedCourseByUserIdAndCourseId(context.Context, *ReadCompletedCourseByUserIdAndCourseIdRequest) (*ReadCompletedCourseByUserIdAndCourseIdResponse, error)
	ReadAllCompletedCoursesByCourseId(context.Context, *ReadAllCompletedCoursesByCourseIdRequest) (*ReadAllCompletedCoursesByCourseIdResponse, error)
	ReadAllCompletedCoursesByUserId(context.Context, *ReadAllCompletedCoursesByUserIdRequest) (*ReadAllCompletedCoursesByUserIdResponse, error)
	mustEmbedUnimplementedCompletedCourseServiceServer()
}

// UnimplementedCompletedCourseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompletedCourseServiceServer struct{}

func (UnimplementedCompletedCourseServiceServer) CreateCompletedCourse(context.Context, *CreateCompletedCourseRequest) (*CreateCompletedCourseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCompletedCourse not implemented")
}
func (UnimplementedCompletedCourseServiceServer) ReadCompletedCourseByUserIdAndCourseId(context.Context, *ReadCompletedCourseByUserIdAndCourseIdRequest) (*ReadCompletedCourseByUserIdAndCourseIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadCompletedCourseByUserIdAndCourseId not implemented")
}
func (UnimplementedCompletedCourseServiceServer) ReadAllCompletedCoursesByCourseId(context.Context, *ReadAllCompletedCoursesByCourseIdRequest) (*ReadAllCompletedCoursesByCourseIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadAllCompletedCoursesByCourseId not implemented")
}
func (UnimplementedCompletedCourseServiceServer) ReadAllCompletedCoursesByUserId(context.Context, *ReadAllCompletedCoursesByUserIdRequest) (*ReadAllCompletedCoursesByUserIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadAllCompletedCoursesByUserId not implemented")
}
func (UnimplementedCompletedCourseServiceServer) mustEmbedUnimplementedCompletedCourseServiceServer() {
}
func (UnimplementedCompletedCourseServiceServer) testEmbeddedByValue() {}

// UnsafeCompletedCourseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompletedCourseServiceServer will
// result in compilation errors.
type UnsafeCompletedCourseServiceServer interface {
	mustEmbedUnimplementedCompletedCourseServiceServer()
}

func RegisterCompletedCourseServiceServer(s grpc.ServiceRegistrar, srv CompletedCourseServiceServer) {
	// If the following call panics, it indicates UnimplementedCompletedCourseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CompletedCourseService_ServiceDesc, srv)
}

func _CompletedCourseService_CreateCompletedCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompletedCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompletedCourseServiceServer).CreateCompletedCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompletedCourseService_CreateCompletedCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompletedCourseServiceServer).CreateCompletedCourse(ctx, req.(*CreateCompletedCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompletedCourseService_ReadCompletedCourseByUserIdAndCourseId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadCompletedCourseByUserIdAndCourseIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompletedCourseServiceServer).ReadCompletedCourseByUserIdAndCourseId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompletedCourseService_ReadCompletedCourseByUserIdAndCourseId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompletedCourseServiceServer).ReadCompletedCourseByUserIdAndCourseId(ctx, req.(*ReadCompletedCourseByUserIdAndCourseIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompletedCourseService_ReadAllCompletedCoursesByCourseId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllCompletedCoursesByCourseIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompletedCourseServiceServer).ReadAllCompletedCoursesByCourseId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompletedCourseService_ReadAllCompletedCoursesByCourseId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompletedCourseServiceServer).ReadAllCompletedCoursesByCourseId(ctx, req.(*ReadAllCompletedCoursesByCourseIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompletedCourseService_ReadAllCompletedCoursesByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllCompletedCoursesByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompletedCourseServiceServer).ReadAllCompletedCoursesByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompletedCourseService_ReadAllCompletedCoursesByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompletedCourseServiceServer).ReadAllCompletedCoursesByUserId(ctx, req.(*ReadAllCompletedCoursesByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CompletedCourseService_ServiceDesc is the grpc.ServiceDesc for CompletedCourseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CompletedCourseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "completedcourseservice.CompletedCourseService",
	HandlerType: (*CompletedCourseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCompletedCourse",
			Handler:    _CompletedCourseService_CreateCompletedCourse_Handler,
		},
		{
			MethodName: "ReadCompletedCourseByUserIdAndCourseId",
			Handler:    _CompletedCourseService_ReadCompletedCourseByUserIdAndCourseId_Handler,
		},
		{
			MethodName: "ReadAllCompletedCoursesByCourseId",
			Handler:    _CompletedCourseService_ReadAllCompletedCoursesByCourseId_Handler,
		},
		{
			MethodName: "ReadAllCompletedCoursesByUserId",
			Handler:    _CompletedCourseService_ReadAllCompletedCoursesByUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/completed_course_service.proto",
}
