// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/lesson_progress_service.proto

package lessonprogressservicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LessonProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LessonId      string                 `protobuf:"bytes,2,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonProgress) Reset() {
	*x = LessonProgress{}
	mi := &file_proto_lesson_progress_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonProgress) ProtoMessage() {}

func (x *LessonProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_progress_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonProgress.ProtoReflect.Descriptor instead.
func (*LessonProgress) Descriptor() ([]byte, []int) {
	return file_proto_lesson_progress_service_proto_rawDescGZIP(), []int{0}
}

func (x *LessonProgress) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LessonProgress) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

type CreateLessonProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LessonId      string                 `protobuf:"bytes,2,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLessonProgressRequest) Reset() {
	*x = CreateLessonProgressRequest{}
	mi := &file_proto_lesson_progress_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLessonProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLessonProgressRequest) ProtoMessage() {}

func (x *CreateLessonProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_progress_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLessonProgressRequest.ProtoReflect.Descriptor instead.
func (*CreateLessonProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_progress_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLessonProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateLessonProgressRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

type CreateLessonProgressResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LessonProgress *LessonProgress        `protobuf:"bytes,1,opt,name=lesson_progress,json=lessonProgress,proto3" json:"lesson_progress,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateLessonProgressResponse) Reset() {
	*x = CreateLessonProgressResponse{}
	mi := &file_proto_lesson_progress_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLessonProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLessonProgressResponse) ProtoMessage() {}

func (x *CreateLessonProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_progress_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLessonProgressResponse.ProtoReflect.Descriptor instead.
func (*CreateLessonProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_progress_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLessonProgressResponse) GetLessonProgress() *LessonProgress {
	if x != nil {
		return x.LessonProgress
	}
	return nil
}

type ReadLessonProgressByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadLessonProgressByUserIdRequest) Reset() {
	*x = ReadLessonProgressByUserIdRequest{}
	mi := &file_proto_lesson_progress_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLessonProgressByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLessonProgressByUserIdRequest) ProtoMessage() {}

func (x *ReadLessonProgressByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_progress_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLessonProgressByUserIdRequest.ProtoReflect.Descriptor instead.
func (*ReadLessonProgressByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_progress_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReadLessonProgressByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ReadLessonProgressByUserIdResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LessonProgresses []*LessonProgress      `protobuf:"bytes,1,rep,name=lesson_progresses,json=lessonProgresses,proto3" json:"lesson_progresses,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReadLessonProgressByUserIdResponse) Reset() {
	*x = ReadLessonProgressByUserIdResponse{}
	mi := &file_proto_lesson_progress_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLessonProgressByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLessonProgressByUserIdResponse) ProtoMessage() {}

func (x *ReadLessonProgressByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_progress_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLessonProgressByUserIdResponse.ProtoReflect.Descriptor instead.
func (*ReadLessonProgressByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_progress_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReadLessonProgressByUserIdResponse) GetLessonProgresses() []*LessonProgress {
	if x != nil {
		return x.LessonProgresses
	}
	return nil
}

type ReadLessonProgressByUserIdAndLessonIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LessonId      string                 `protobuf:"bytes,2,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadLessonProgressByUserIdAndLessonIdRequest) Reset() {
	*x = ReadLessonProgressByUserIdAndLessonIdRequest{}
	mi := &file_proto_lesson_progress_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLessonProgressByUserIdAndLessonIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLessonProgressByUserIdAndLessonIdRequest) ProtoMessage() {}

func (x *ReadLessonProgressByUserIdAndLessonIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_progress_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLessonProgressByUserIdAndLessonIdRequest.ProtoReflect.Descriptor instead.
func (*ReadLessonProgressByUserIdAndLessonIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_progress_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReadLessonProgressByUserIdAndLessonIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReadLessonProgressByUserIdAndLessonIdRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

type ReadLessonProgressByUserIdAndLessonIdResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LessonProgress *LessonProgress        `protobuf:"bytes,1,opt,name=lesson_progress,json=lessonProgress,proto3" json:"lesson_progress,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadLessonProgressByUserIdAndLessonIdResponse) Reset() {
	*x = ReadLessonProgressByUserIdAndLessonIdResponse{}
	mi := &file_proto_lesson_progress_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLessonProgressByUserIdAndLessonIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLessonProgressByUserIdAndLessonIdResponse) ProtoMessage() {}

func (x *ReadLessonProgressByUserIdAndLessonIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_progress_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLessonProgressByUserIdAndLessonIdResponse.ProtoReflect.Descriptor instead.
func (*ReadLessonProgressByUserIdAndLessonIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_progress_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReadLessonProgressByUserIdAndLessonIdResponse) GetLessonProgress() *LessonProgress {
	if x != nil {
		return x.LessonProgress
	}
	return nil
}

type ModuleProgress struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ModuleId           string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	TotalLessons       int64                  `protobuf:"varint,2,opt,name=total_lessons,json=totalLessons,proto3" json:"total_lessons,omitempty"`
	CompletedLessons   int64                  `protobuf:"varint,3,opt,name=completed_lessons,json=completedLessons,proto3" json:"completed_lessons,omitempty"`
	ProgressPercent    float64                `protobuf:"fixed64,4,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	CompletedLessonIds []string               `protobuf:"bytes,5,rep,name=completed_lesson_ids,json=completedLessonIds,proto3" json:"completed_lesson_ids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ModuleProgress) Reset() {
	*x = ModuleProgress{}
	mi := &file_proto_lesson_progress_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleProgress) ProtoMessage() {}

func (x *ModuleProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_progress_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleProgress.ProtoReflect.Descriptor instead.
func (*ModuleProgress) Descriptor() ([]byte, []int) {
	return file_proto_lesson_progress_service_proto_rawDescGZIP(), []int{7}
}

func (x *ModuleProgress) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *ModuleProgress) GetTotalLessons() int64 {
	if x != nil {
		return x.TotalLessons
	}
	return 0
}

func (x *ModuleProgress) GetCompletedLessons() int64 {
	if x != nil {
		return x.CompletedLessons
	}
	return 0
}

func (x *ModuleProgress) GetProgressPercent() float64 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *ModuleProgress) GetCompletedLessonIds() []string {
	if x != nil {
		return x.CompletedLessonIds
	}
	return nil
}

type UserModuleProgress struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompletedLessons int64                  `protobuf:"varint,2,opt,name=completed_lessons,json=completedLessons,proto3" json:"completed_lessons,omitempty"`
	TotalLessons     int64                  `protobuf:"varint,3,opt,name=total_lessons,json=totalLessons,proto3" json:"total_lessons,omitempty"`
	ProgressPercent  float64                `protobuf:"fixed64,4,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	Completed        bool                   `protobuf:"varint,5,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserModuleProgress) Reset() {
	*x = UserModuleProgress{}
	mi := &file_proto_lesson_progress_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserModuleProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserModuleProgress) ProtoMessage() {}

func (x *UserModuleProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_progress_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserModuleProgress.ProtoReflect.Descriptor instead.
func (*UserModuleProgress) Descriptor() ([]byte, []int) {
	return file_proto_lesson_progress_service_proto_rawDescGZIP(), []int{8}
}

func (x *UserModuleProgress) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserModuleProgress) GetCompletedLessons() int64 {
	if x != nil {
		return x.CompletedLessons
	}
	return 0
}

func (x *UserModuleProgress) GetTotalLessons() int64 {
	if x != nil {
		return x.TotalLessons
	}
	return 0
}

func (x *UserModuleProgress) GetProgressPercent() float64 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *UserModuleProgress) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type ModuleStatistics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	UsersProgress []*UserModuleProgress  `protobuf:"bytes,2,rep,name=users_progress,json=usersProgress,proto3" json:"users_progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleStatistics) Reset() {
	*x = ModuleStatistics{}
	mi := &file_proto_lesson_progress_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleStatistics) ProtoMessage() {}

func (x *ModuleStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_progress_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleStatistics.ProtoReflect.Descriptor instead.
func (*ModuleStatistics) Descriptor() ([]byte, []int) {
	return file_proto_lesson_progress_service_proto_rawDescGZIP(), []int{9}
}

func (x *ModuleStatistics) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *ModuleStatistics) GetUsersProgress() []*UserModuleProgress {
	if x != nil {
		return x.UsersProgress
	}
	return nil
}

type ReadModuleProgressByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ModuleId      string                 `protobuf:"bytes,2,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadModuleProgressByUserIdRequest) Reset() {
	*x = ReadModuleProgressByUserIdRequest{}
	mi := &file_proto_lesson_progress_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadModuleProgressByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadModuleProgressByUserIdRequest) ProtoMessage() {}

func (x *ReadModuleProgressByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_progress_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadModuleProgressByUserIdRequest.ProtoReflect.Descriptor instead.
func (*ReadModuleProgressByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_progress_service_proto_rawDescGZIP(), []int{10}
}

func (x *ReadModuleProgressByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReadModuleProgressByUserIdRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

type ReadModuleProgressByUserIdResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ModuleProgress *ModuleProgress        `protobuf:"bytes,1,opt,name=module_progress,json=moduleProgress,proto3" json:"module_progress,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadModuleProgressByUserIdResponse) Reset() {
	*x = ReadModuleProgressByUserIdResponse{}
	mi := &file_proto_lesson_progress_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadModuleProgressByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadModuleProgressByUserIdResponse) ProtoMessage() {}

func (x *ReadModuleProgressByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_progress_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadModuleProgressByUserIdResponse.ProtoReflect.Descriptor instead.
func (*ReadModuleProgressByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_progress_service_proto_rawDescGZIP(), []int{11}
}

func (x *ReadModuleProgressByUserIdResponse) GetModuleProgress() *ModuleProgress {
	if x != nil {
		return x.ModuleProgress
	}
	return nil
}

type ReadModuleStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadModuleStatisticsRequest) Reset() {
	*x = ReadModuleStatisticsRequest{}
	mi := &file_proto_lesson_progress_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadModuleStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadModuleStatisticsRequest) ProtoMessage() {}

func (x *ReadModuleStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_progress_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadModuleStatisticsRequest.ProtoReflect.Descriptor instead.
func (*ReadModuleStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_progress_service_proto_rawDescGZIP(), []int{12}
}

func (x *ReadModuleStatisticsRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

type ReadModuleStatisticsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ModuleStatistics *ModuleStatistics      `protobuf:"bytes,1,opt,name=module_statistics,json=moduleStatistics,proto3" json:"module_statistics,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReadModuleStatisticsResponse) Reset() {
	*x = ReadModuleStatisticsResponse{}
	mi := &file_proto_lesson_progress_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadModuleStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadModuleStatisticsResponse) ProtoMessage() {}

func (x *ReadModuleStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_progress_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadModuleStatisticsResponse.ProtoReflect.Descriptor instead.
func (*ReadModuleStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_progress_service_proto_rawDescGZIP(), []int{13}
}

func (x *ReadModuleStatisticsResponse) GetModuleStatistics() *ModuleStatistics {
	if x != nil {
		return x.ModuleStatistics
	}
	return nil
}

type CourseProgress struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CourseId           string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	TotalLessons       int64                  `protobuf:"varint,2,opt,name=total_lessons,json=totalLessons,proto3" json:"total_lessons,omitempty"`
	CompletedLessons   int64                  `protobuf:"varint,3,opt,name=completed_lessons,json=completedLessons,proto3" json:"completed_lessons,omitempty"`
	ProgressPercent    float64                `protobuf:"fixed64,4,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	CompletedLessonIds []string               `protobuf:"bytes,5,rep,name=completed_lesson_ids,json=completedLessonIds,proto3" json:"completed_lesson_ids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CourseProgress) Reset() {
	*x = CourseProgress{}
	mi := &file_proto_lesson_progress_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseProgress) ProtoMessage() {}

func (x *CourseProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_progress_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseProgress.ProtoReflect.Descriptor instead.
func (*CourseProgress) Descriptor() ([]byte, []int) {
	return file_proto_lesson_progress_service_proto_rawDescGZIP(), []int{14}
}

func (x *CourseProgress) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CourseProgress) GetTotalLessons() int64 {
	if x != nil {
		return x.TotalLessons
	}
	return 0
}

func (x *CourseProgress) GetCompletedLessons() int64 {
	if x != nil {
		return x.CompletedLessons
	}
	return 0
}

func (x *CourseProgress) GetProgressPercent() float64 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *CourseProgress) GetCompletedLessonIds() []string {
	if x != nil {
		return x.CompletedLessonIds
	}
	return nil
}

type UserCourseProgress struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompletedLessons int64                  `protobuf:"varint,2,opt,name=completed_lessons,json=completedLessons,proto3" json:"completed_lessons,omitempty"`
	TotalLessons     int64                  `protobuf:"varint,3,opt,name=total_lessons,json=totalLessons,proto3" json:"total_lessons,omitempty"`
	ProgressPercent  float64                `protobuf:"fixed64,4,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	Completed        bool                   `protobuf:"varint,5,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserCourseProgress) Reset() {
	*x = UserCourseProgress{}
	mi := &file_proto_lesson_progress_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCourseProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCourseProgress) ProtoMessage() {}

func (x *UserCourseProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_progress_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCourseProgress.ProtoReflect.Descriptor instead.
func (*UserCourseProgress) Descriptor() ([]byte, []int) {
	return file_proto_lesson_progress_service_proto_rawDescGZIP(), []int{15}
}

func (x *UserCourseProgress) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserCourseProgress) GetCompletedLessons() int64 {
	if x != nil {
		return x.CompletedLessons
	}
	return 0
}

func (x *UserCourseProgress) GetTotalLessons() int64 {
	if x != nil {
		return x.TotalLessons
	}
	return 0
}

func (x *UserCourseProgress) GetProgressPercent() float64 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *UserCourseProgress) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type ReadCourseProgressByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCourseProgressByUserIdRequest) Reset() {
	*x = ReadCourseProgressByUserIdRequest{}
	mi := &file_proto_lesson_progress_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCourseProgressByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCourseProgressByUserIdRequest) ProtoMessage() {}

func (x *ReadCourseProgressByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_progress_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCourseProgressByUserIdRequest.ProtoReflect.Descriptor instead.
func (*ReadCourseProgressByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_progress_service_proto_rawDescGZIP(), []int{16}
}

func (x *ReadCourseProgressByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReadCourseProgressByUserIdRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type ReadCourseProgressByUserIdResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CourseProgress *CourseProgress        `protobuf:"bytes,1,opt,name=course_progress,json=courseProgress,proto3" json:"course_progress,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadCourseProgressByUserIdResponse) Reset() {
	*x = ReadCourseProgressByUserIdResponse{}
	mi := &file_proto_lesson_progress_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCourseProgressByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCourseProgressByUserIdResponse) ProtoMessage() {}

func (x *ReadCourseProgressByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_progress_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCourseProgressByUserIdResponse.ProtoReflect.Descriptor instead.
func (*ReadCourseProgressByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_progress_service_proto_rawDescGZIP(), []int{17}
}

func (x *ReadCourseProgressByUserIdResponse) GetCourseProgress() *CourseProgress {
	if x != nil {
		return x.CourseProgress
	}
	return nil
}

type CourseStatistics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	UsersProgress []*UserCourseProgress  `protobuf:"bytes,2,rep,name=users_progress,json=usersProgress,proto3" json:"users_progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseStatistics) Reset() {
	*x = CourseStatistics{}
	mi := &file_proto_lesson_progress_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseStatistics) ProtoMessage() {}

func (x *CourseStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_progress_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseStatistics.ProtoReflect.Descriptor instead.
func (*CourseStatistics) Descriptor() ([]byte, []int) {
	return file_proto_lesson_progress_service_proto_rawDescGZIP(), []int{18}
}

func (x *CourseStatistics) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CourseStatistics) GetUsersProgress() []*UserCourseProgress {
	if x != nil {
		return x.UsersProgress
	}
	return nil
}

type ReadCourseStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCourseStatisticsRequest) Reset() {
	*x = ReadCourseStatisticsRequest{}
	mi := &file_proto_lesson_progress_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCourseStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCourseStatisticsRequest) ProtoMessage() {}

func (x *ReadCourseStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_progress_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCourseStatisticsRequest.ProtoReflect.Descriptor instead.
func (*ReadCourseStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_progress_service_proto_rawDescGZIP(), []int{19}
}

func (x *ReadCourseStatisticsRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type ReadCourseStatisticsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CourseStatistics *CourseStatistics      `protobuf:"bytes,1,opt,name=course_statistics,json=courseStatistics,proto3" json:"course_statistics,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReadCourseStatisticsResponse) Reset() {
	*x = ReadCourseStatisticsResponse{}
	mi := &file_proto_lesson_progress_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCourseStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCourseStatisticsResponse) ProtoMessage() {}

func (x *ReadCourseStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_progress_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCourseStatisticsResponse.ProtoReflect.Descriptor instead.
func (*ReadCourseStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_progress_service_proto_rawDescGZIP(), []int{20}
}

func (x *ReadCourseStatisticsResponse) GetCourseStatistics() *CourseStatistics {
	if x != nil {
		return x.CourseStatistics
	}
	return nil
}

var File_proto_lesson_progress_service_proto protoreflect.FileDescriptor

const file_proto_lesson_progress_service_proto_rawDesc = "" +
	"\n" +
	"#proto/lesson_progress_service.proto\x12\x15lessonprogressservice\"F\n" +
	"\x0eLessonProgress\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tlesson_id\x18\x02 \x01(\tR\blessonId\"S\n" +
	"\x1bCreateLessonProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tlesson_id\x18\x02 \x01(\tR\blessonId\"n\n" +
	"\x1cCreateLessonProgressResponse\x12N\n" +
	"\x0flesson_progress\x18\x01 \x01(\v2%.lessonprogressservice.LessonProgressR\x0elessonProgress\"<\n" +
	"!ReadLessonProgressByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"x\n" +
	"\"ReadLessonProgressByUserIdResponse\x12R\n" +
	"\x11lesson_progresses\x18\x01 \x03(\v2%.lessonprogressservice.LessonProgressR\x10lessonProgresses\"d\n" +
	",ReadLessonProgressByUserIdAndLessonIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tlesson_id\x18\x02 \x01(\tR\blessonId\"\x7f\n" +
	"-ReadLessonProgressByUserIdAndLessonIdResponse\x12N\n" +
	"\x0flesson_progress\x18\x01 \x01(\v2%.lessonprogressservice.LessonProgressR\x0elessonProgress\"\xdc\x01\n" +
	"\x0eModuleProgress\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\x12#\n" +
	"\rtotal_lessons\x18\x02 \x01(\x03R\ftotalLessons\x12+\n" +
	"\x11completed_lessons\x18\x03 \x01(\x03R\x10completedLessons\x12)\n" +
	"\x10progress_percent\x18\x04 \x01(\x01R\x0fprogressPercent\x120\n" +
	"\x14completed_lesson_ids\x18\x05 \x03(\tR\x12completedLessonIds\"\xc8\x01\n" +
	"\x12UserModuleProgress\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x11completed_lessons\x18\x02 \x01(\x03R\x10completedLessons\x12#\n" +
	"\rtotal_lessons\x18\x03 \x01(\x03R\ftotalLessons\x12)\n" +
	"\x10progress_percent\x18\x04 \x01(\x01R\x0fprogressPercent\x12\x1c\n" +
	"\tcompleted\x18\x05 \x01(\bR\tcompleted\"\x81\x01\n" +
	"\x10ModuleStatistics\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\x12P\n" +
	"\x0eusers_progress\x18\x02 \x03(\v2).lessonprogressservice.UserModuleProgressR\rusersProgress\"Y\n" +
	"!ReadModuleProgressByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tmodule_id\x18\x02 \x01(\tR\bmoduleId\"t\n" +
	"\"ReadModuleProgressByUserIdResponse\x12N\n" +
	"\x0fmodule_progress\x18\x01 \x01(\v2%.lessonprogressservice.ModuleProgressR\x0emoduleProgress\":\n" +
	"\x1bReadModuleStatisticsRequest\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\"t\n" +
	"\x1cReadModuleStatisticsResponse\x12T\n" +
	"\x11module_statistics\x18\x01 \x01(\v2'.lessonprogressservice.ModuleStatisticsR\x10moduleStatistics\"\xdc\x01\n" +
	"\x0eCourseProgress\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12#\n" +
	"\rtotal_lessons\x18\x02 \x01(\x03R\ftotalLessons\x12+\n" +
	"\x11completed_lessons\x18\x03 \x01(\x03R\x10completedLessons\x12)\n" +
	"\x10progress_percent\x18\x04 \x01(\x01R\x0fprogressPercent\x120\n" +
	"\x14completed_lesson_ids\x18\x05 \x03(\tR\x12completedLessonIds\"\xc8\x01\n" +
	"\x12UserCourseProgress\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x11completed_lessons\x18\x02 \x01(\x03R\x10completedLessons\x12#\n" +
	"\rtotal_lessons\x18\x03 \x01(\x03R\ftotalLessons\x12)\n" +
	"\x10progress_percent\x18\x04 \x01(\x01R\x0fprogressPercent\x12\x1c\n" +
	"\tcompleted\x18\x05 \x01(\bR\tcompleted\"Y\n" +
	"!ReadCourseProgressByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"t\n" +
	"\"ReadCourseProgressByUserIdResponse\x12N\n" +
	"\x0fcourse_progress\x18\x01 \x01(\v2%.lessonprogressservice.CourseProgressR\x0ecourseProgress\"\x81\x01\n" +
	"\x10CourseStatistics\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12P\n" +
	"\x0eusers_progress\x18\x02 \x03(\v2).lessonprogressservice.UserCourseProgressR\rusersProgress\":\n" +
	"\x1bReadCourseStatisticsRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"t\n" +
	"\x1cReadCourseStatisticsResponse\x12T\n" +
	"\x11course_statistics\x18\x01 \x01(\v2'.lessonprogressservice.CourseStatisticsR\x10courseStatistics2\x8b\b\n" +
	"\x15LessonProgressService\x12\x7f\n" +
	"\x14CreateLessonProgress\x122.lessonprogressservice.CreateLessonProgressRequest\x1a3.lessonprogressservice.CreateLessonProgressResponse\x12\x91\x01\n" +
	"\x1aReadLessonProgressByUserId\x128.lessonprogressservice.ReadLessonProgressByUserIdRequest\x1a9.lessonprogressservice.ReadLessonProgressByUserIdResponse\x12\xb2\x01\n" +
	"%ReadLessonProgressByUserIdAndLessonId\x12C.lessonprogressservice.ReadLessonProgressByUserIdAndLessonIdRequest\x1aD.lessonprogressservice.ReadLessonProgressByUserIdAndLessonIdResponse\x12\x91\x01\n" +
	"\x1aReadModuleProgressByUserId\x128.lessonprogressservice.ReadModuleProgressByUserIdRequest\x1a9.lessonprogressservice.ReadModuleProgressByUserIdResponse\x12\x7f\n" +
	"\x14ReadModuleStatistics\x122.lessonprogressservice.ReadModuleStatisticsRequest\x1a3.lessonprogressservice.ReadModuleStatisticsResponse\x12\x91\x01\n" +
	"\x1aReadCourseProgressByUserId\x128.lessonprogressservice.ReadCourseProgressByUserIdRequest\x1a9.lessonprogressservice.ReadCourseProgressByUserIdResponse\x12\x7f\n" +
	"\x14ReadCourseStatistics\x122.lessonprogressservice.ReadCourseStatisticsRequest\x1a3.lessonprogressservice.ReadCourseStatisticsResponseB\x1fZ\x1dproto/lessonprogressservicepbb\x06proto3"

var (
	file_proto_lesson_progress_service_proto_rawDescOnce sync.Once
	file_proto_lesson_progress_service_proto_rawDescData []byte
)

func file_proto_lesson_progress_service_proto_rawDescGZIP() []byte {
	file_proto_lesson_progress_service_proto_rawDescOnce.Do(func() {
		file_proto_lesson_progress_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lesson_progress_service_proto_rawDesc), len(file_proto_lesson_progress_service_proto_rawDesc)))
	})
	return file_proto_lesson_progress_service_proto_rawDescData
}

var file_proto_lesson_progress_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_lesson_progress_service_proto_goTypes = []any{
	(*LessonProgress)(nil),                                // 0: lessonprogressservice.LessonProgress
	(*CreateLessonProgressRequest)(nil),                   // 1: lessonprogressservice.CreateLessonProgressRequest
	(*CreateLessonProgressResponse)(nil),                  // 2: lessonprogressservice.CreateLessonProgressResponse
	(*ReadLessonProgressByUserIdRequest)(nil),             // 3: lessonprogressservice.ReadLessonProgressByUserIdRequest
	(*ReadLessonProgressByUserIdResponse)(nil),            // 4: lessonprogressservice.ReadLessonProgressByUserIdResponse
	(*ReadLessonProgressByUserIdAndLessonIdRequest)(nil),  // 5: lessonprogressservice.ReadLessonProgressByUserIdAndLessonIdRequest
	(*ReadLessonProgressByUserIdAndLessonIdResponse)(nil), // 6: lessonprogressservice.ReadLessonProgressByUserIdAndLessonIdResponse
	(*ModuleProgress)(nil),                                // 7: lessonprogressservice.ModuleProgress
	(*UserModuleProgress)(nil),                            // 8: lessonprogressservice.UserModuleProgress
	(*ModuleStatistics)(nil),                              // 9: lessonprogressservice.ModuleStatistics
	(*ReadModuleProgressByUserIdRequest)(nil),             // 10: lessonprogressservice.ReadModuleProgressByUserIdRequest
	(*ReadModuleProgressByUserIdResponse)(nil),            // 11: lessonprogressservice.ReadModuleProgressByUserIdResponse
	(*ReadModuleStatisticsRequest)(nil),                   // 12: lessonprogressservice.ReadModuleStatisticsRequest
	(*ReadModuleStatisticsResponse)(nil),                  // 13: lessonprogressservice.ReadModuleStatisticsResponse
	(*CourseProgress)(nil),                                // 14: lessonprogressservice.CourseProgress
	(*UserCourseProgress)(nil),                            // 15: lessonprogressservice.UserCourseProgress
	(*ReadCourseProgressByUserIdRequest)(nil),             // 16: lessonprogressservice.ReadCourseProgressByUserIdRequest
	(*ReadCourseProgressByUserIdResponse)(nil),            // 17: lessonprogressservice.ReadCourseProgressByUserIdResponse
	(*CourseStatistics)(nil),                              // 18: lessonprogressservice.CourseStatistics
	(*ReadCourseStatisticsRequest)(nil),                   // 19: lessonprogressservice.ReadCourseStatisticsRequest
	(*ReadCourseStatisticsResponse)(nil),                  // 20: lessonprogressservice.ReadCourseStatisticsResponse
}
var file_proto_lesson_progress_service_proto_depIdxs = []int32{
	0,  // 0: lessonprogressservice.CreateLessonProgressResponse.lesson_progress:type_name -> lessonprogressservice.LessonProgress
	0,  // 1: lessonprogressservice.ReadLessonProgressByUserIdResponse.lesson_progresses:type_name -> lessonprogressservice.LessonProgress
	0,  // 2: lessonprogressservice.ReadLessonProgressByUserIdAndLessonIdResponse.lesson_progress:type_name -> lessonprogressservice.LessonProgress
	8,  // 3: lessonprogressservice.ModuleStatistics.users_progress:type_name -> lessonprogressservice.UserModuleProgress
	7,  // 4: lessonprogressservice.ReadModuleProgressByUserIdResponse.module_progress:type_name -> lessonprogressservice.ModuleProgress
	9,  // 5: lessonprogressservice.ReadModuleStatisticsResponse.module_statistics:type_name -> lessonprogressservice.ModuleStatistics
	14, // 6: lessonprogressservice.ReadCourseProgressByUserIdResponse.course_progress:type_name -> lessonprogressservice.CourseProgress
	15, // 7: lessonprogressservice.CourseStatistics.users_progress:type_name -> lessonprogressservice.UserCourseProgress
	18, // 8: lessonprogressservice.ReadCourseStatisticsResponse.course_statistics:type_name -> lessonprogressservice.CourseStatistics
	1,  // 9: lessonprogressservice.LessonProgressService.CreateLessonProgress:input_type -> lessonprogressservice.CreateLessonProgressRequest
	3,  // 10: lessonprogressservice.LessonProgressService.ReadLessonProgressByUserId:input_type -> lessonprogressservice.ReadLessonProgressByUserIdRequest
	5,  // 11: lessonprogressservice.LessonProgressService.ReadLessonProgressByUserIdAndLessonId:input_type -> lessonprogressservice.ReadLessonProgressByUserIdAndLessonIdRequest
	10, // 12: lessonprogressservice.LessonProgressService.ReadModuleProgressByUserId:input_type -> lessonprogressservice.ReadModuleProgressByUserIdRequest
	12, // 13: lessonprogressservice.LessonProgressService.ReadModuleStatistics:input_type -> lessonprogressservice.ReadModuleStatisticsRequest
	16, // 14: lessonprogressservice.LessonProgressService.ReadCourseProgressByUserId:input_type -> lessonprogressservice.ReadCourseProgressByUserIdRequest
	19, // 15: lessonprogressservice.LessonProgressService.ReadCourseStatistics:input_type -> lessonprogressservice.ReadCourseStatisticsRequest
	2,  // 16: lessonprogressservice.LessonProgressService.CreateLessonProgress:output_type -> lessonprogressservice.CreateLessonProgressResponse
	4,  // 17: lessonprogressservice.LessonProgressService.ReadLessonProgressByUserId:output_type -> lessonprogressservice.ReadLessonProgressByUserIdResponse
	6,  // 18: lessonprogressservice.LessonProgressService.ReadLessonProgressByUserIdAndLessonId:output_type -> lessonprogressservice.ReadLessonProgressByUserIdAndLessonIdResponse
	11, // 19: lessonprogressservice.LessonProgressService.ReadModuleProgressByUserId:output_type -> lessonprogressservice.ReadModuleProgressByUserIdResponse
	13, // 20: lessonprogressservice.LessonProgressService.ReadModuleStatistics:output_type -> lessonprogressservice.ReadModuleStatisticsResponse
	17, // 21: lessonprogressservice.LessonProgressService.ReadCourseProgressByUserId:output_type -> lessonprogressservice.ReadCourseProgressByUserIdResponse
	20, // 22: lessonprogressservice.LessonProgressService.ReadCourseStatistics:output_type -> lessonprogressservice.ReadCourseStatisticsResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_lesson_progress_service_proto_init() }
func file_proto_lesson_progress_service_proto_init() {
	if File_proto_lesson_progress_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lesson_progress_service_proto_rawDesc), len(file_proto_lesson_progress_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lesson_progress_service_proto_goTypes,
		DependencyIndexes: file_proto_lesson_progress_service_proto_depIdxs,
		MessageInfos:      file_proto_lesson_progress_service_proto_msgTypes,
	}.Build()
	File_proto_lesson_progress_service_proto = out.File
	file_proto_lesson_progress_service_proto_goTypes = nil
	file_proto_lesson_progress_service_proto_depIdxs = nil
}
