// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: proto/lesson_progress_service.proto

package lessonprogressservicepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LessonProgressService_CreateLessonProgress_FullMethodName                  = "/lessonprogressservice.LessonProgressService/CreateLessonProgress"
	LessonProgressService_ReadLessonProgressByUserId_FullMethodName            = "/lessonprogressservice.LessonProgressService/ReadLessonProgressByUserId"
	LessonProgressService_ReadLessonProgressByUserIdAndLessonId_FullMethodName = "/lessonprogressservice.LessonProgressService/ReadLessonProgressByUserIdAndLessonId"
	LessonProgressService_ReadModuleProgressByUserId_FullMethodName            = "/lessonprogressservice.LessonProgressService/ReadModuleProgressByUserId"
	LessonProgressService_ReadModuleStatistics_FullMethodName                  = "/lessonprogressservice.LessonProgressService/ReadModuleStatistics"
	LessonProgressService_ReadCourseProgressByUserId_FullMethodName            = "/lessonprogressservice.LessonProgressService/ReadCourseProgressByUserId"
	LessonProgressService_ReadCourseStatistics_FullMethodName                  = "/lessonprogressservice.LessonProgressService/ReadCourseStatistics"
)

// LessonProgressServiceClient is the client API for LessonProgressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LessonProgressServiceClient interface {
	CreateLessonProgress(ctx context.Context, in *CreateLessonProgressRequest, opts ...grpc.CallOption) (*CreateLessonProgressResponse, error)
	ReadLessonProgressByUserId(ctx context.Context, in *ReadLessonProgressByUserIdRequest, opts ...grpc.CallOption) (*ReadLessonProgressByUserIdResponse, error)
	ReadLessonProgressByUserIdAndLessonId(ctx context.Context, in *ReadLessonProgressByUserIdAndLessonIdRequest, opts ...grpc.CallOption) (*ReadLessonProgressByUserIdAndLessonIdResponse, error)
	ReadModuleProgressByUserId(ctx context.Context, in *ReadModuleProgressByUserIdRequest, opts ...grpc.CallOption) (*ReadModuleProgressByUserIdResponse, error)
	ReadModuleStatistics(ctx context.Context, in *ReadModuleStatisticsRequest, opts ...grpc.CallOption) (*ReadModuleStatisticsResponse, error)
	ReadCourseProgressByUserId(ctx context.Context, in *ReadCourseProgressByUserIdRequest, opts ...grpc.CallOption) (*ReadCourseProgressByUserIdResponse, error)
	ReadCourseStatistics(ctx context.Context, in *ReadCourseStatisticsRequest, opts ...grpc.CallOption) (*ReadCourseStatisticsResponse, error)
}

type lessonProgressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLessonProgressServiceClient(cc grpc.ClientConnInterface) LessonProgressServiceClient {
	return &lessonProgressServiceClient{cc}
}

func (c *lessonProgressServiceClient) CreateLessonProgress(ctx context.Context, in *CreateLessonProgressRequest, opts ...grpc.CallOption) (*CreateLessonProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLessonProgressResponse)
	err := c.cc.Invoke(ctx, LessonProgressService_CreateLessonProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonProgressServiceClient) ReadLessonProgressByUserId(ctx context.Context, in *ReadLessonProgressByUserIdRequest, opts ...grpc.CallOption) (*ReadLessonProgressByUserIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadLessonProgressByUserIdResponse)
	err := c.cc.Invoke(ctx, LessonProgressService_ReadLessonProgressByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonProgressServiceClient) ReadLessonProgressByUserIdAndLessonId(ctx context.Context, in *ReadLessonProgressByUserIdAndLessonIdRequest, opts ...grpc.CallOption) (*ReadLessonProgressByUserIdAndLessonIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadLessonProgressByUserIdAndLessonIdResponse)
	err := c.cc.Invoke(ctx, LessonProgressService_ReadLessonProgressByUserIdAndLessonId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonProgressServiceClient) ReadModuleProgressByUserId(ctx context.Context, in *ReadModuleProgressByUserIdRequest, opts ...grpc.CallOption) (*ReadModuleProgressByUserIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadModuleProgressByUserIdResponse)
	err := c.cc.Invoke(ctx, LessonProgressService_ReadModuleProgressByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonProgressServiceClient) ReadModuleStatistics(ctx context.Context, in *ReadModuleStatisticsRequest, opts ...grpc.CallOption) (*ReadModuleStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadModuleStatisticsResponse)
	err := c.cc.Invoke(ctx, LessonProgressService_ReadModuleStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonProgressServiceClient) ReadCourseProgressByUserId(ctx context.Context, in *ReadCourseProgressByUserIdRequest, opts ...grpc.CallOption) (*ReadCourseProgressByUserIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadCourseProgressByUserIdResponse)
	err := c.cc.Invoke(ctx, LessonProgressService_ReadCourseProgressByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonProgressServiceClient) ReadCourseStatistics(ctx context.Context, in *ReadCourseStatisticsRequest, opts ...grpc.CallOption) (*ReadCourseStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadCourseStatisticsResponse)
	err := c.cc.Invoke(ctx, LessonProgressService_ReadCourseStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LessonProgressServiceServer is the server API for LessonProgressService service.
// All implementations must embed UnimplementedLessonProgressServiceServer
// for forward compatibility.
type LessonProgressServiceServer interface {
	CreateLessonProgress(context.Context, *CreateLessonProgressRequest) (*CreateLessonProgressResponse, error)
	ReadLessonProgressByUserId(context.Context, *ReadLessonProgressByUserIdRequest) (*ReadLessonProgressByUserIdResponse, error)
	ReadLessonProgressByUserIdAndLessonId(context.Context, *ReadLessonProgressByUserIdAndLessonIdRequest) (*ReadLessonProgressByUserIdAndLessonIdResponse, error)
	ReadModuleProgressByUserId(context.Context, *ReadModuleProgressByUserIdRequest) (*ReadModuleProgressByUserIdResponse, error)
	ReadModuleStatistics(context.Context, *ReadModuleStatisticsRequest) (*ReadModuleStatisticsResponse, error)
	ReadCourseProgressByUserId(context.Context, *ReadCourseProgressByUserIdRequest) (*ReadCourseProgressByUserIdResponse, error)
	ReadCourseStatistics(context.Context, *ReadCourseStatisticsRequest) (*ReadCourseStatisticsResponse, error)
	mustEmbedUnimplementedLessonProgressServiceServer()
}

// UnimplementedLessonProgressServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLessonProgressServiceServer struct{}

func (UnimplementedLessonProgressServiceServer) CreateLessonProgress(context.Context, *CreateLessonProgressRequest) (*CreateLessonProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLessonProgress not implemented")
}
func (UnimplementedLessonProgressServiceServer) ReadLessonProgressByUserId(context.Context, *ReadLessonProgressByUserIdRequest) (*ReadLessonProgressByUserIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadLessonProgressByUserId not implemented")
}
func (UnimplementedLessonProgressServiceServer) ReadLessonProgressByUserIdAndLessonId(context.Context, *ReadLessonProgressByUserIdAndLessonIdRequest) (*ReadLessonProgressByUserIdAndLessonIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadLessonProgressByUserIdAndLessonId not implemented")
}
func (UnimplementedLessonProgressServiceServer) ReadModuleProgressByUserId(context.Context, *ReadModuleProgressByUserIdRequest) (*ReadModuleProgressByUserIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadModuleProgressByUserId not implemented")
}
func (UnimplementedLessonProgressServiceServer) ReadModuleStatistics(context.Context, *ReadModuleStatisticsRequest) (*ReadModuleStatisticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadModuleStatistics not implemented")
}
func (UnimplementedLessonProgressServiceServer) ReadCourseProgressByUserId(context.Context, *ReadCourseProgressByUserIdRequest) (*ReadCourseProgressByUserIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadCourseProgressByUserId not implemented")
}
func (UnimplementedLessonProgressServiceServer) ReadCourseStatistics(context.Context, *ReadCourseStatisticsRequest) (*ReadCourseStatisticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadCourseStatistics not implemented")
}
func (UnimplementedLessonProgressServiceServer) mustEmbedUnimplementedLessonProgressServiceServer() {}
func (UnimplementedLessonProgressServiceServer) testEmbeddedByValue()                               {}

// UnsafeLessonProgressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LessonProgressServiceServer will
// result in compilation errors.
type UnsafeLessonProgressServiceServer interface {
	mustEmbedUnimplementedLessonProgressServiceServer()
}

func RegisterLessonProgressServiceServer(s grpc.ServiceRegistrar, srv LessonProgressServiceServer) {
	// If the following call panics, it indicates UnimplementedLessonProgressServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LessonProgressService_ServiceDesc, srv)
}

func _LessonProgressService_CreateLessonProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLessonProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonProgressServiceServer).CreateLessonProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonProgressService_CreateLessonProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonProgressServiceServer).CreateLessonProgress(ctx, req.(*CreateLessonProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonProgressService_ReadLessonProgressByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadLessonProgressByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonProgressServiceServer).ReadLessonProgressByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonProgressService_ReadLessonProgressByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonProgressServiceServer).ReadLessonProgressByUserId(ctx, req.(*ReadLessonProgressByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonProgressService_ReadLessonProgressByUserIdAndLessonId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadLessonProgressByUserIdAndLessonIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonProgressServiceServer).ReadLessonProgressByUserIdAndLessonId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonProgressService_ReadLessonProgressByUserIdAndLessonId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonProgressServiceServer).ReadLessonProgressByUserIdAndLessonId(ctx, req.(*ReadLessonProgressByUserIdAndLessonIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonProgressService_ReadModuleProgressByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadModuleProgressByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonProgressServiceServer).ReadModuleProgressByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonProgressService_ReadModuleProgressByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonProgressServiceServer).ReadModuleProgressByUserId(ctx, req.(*ReadModuleProgressByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonProgressService_ReadModuleStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadModuleStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonProgressServiceServer).ReadModuleStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonProgressService_ReadModuleStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonProgressServiceServer).ReadModuleStatistics(ctx, req.(*ReadModuleStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonProgressService_ReadCourseProgressByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadCourseProgressByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonProgressServiceServer).ReadCourseProgressByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonProgressService_ReadCourseProgressByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonProgressServiceServer).ReadCourseProgressByUserId(ctx, req.(*ReadCourseProgressByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonProgressService_ReadCourseStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadCourseStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonProgressServiceServer).ReadCourseStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonProgressService_ReadCourseStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonProgressServiceServer).ReadCourseStatistics(ctx, req.(*ReadCourseStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LessonProgressService_ServiceDesc is the grpc.ServiceDesc for LessonProgressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LessonProgressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lessonprogressservice.LessonProgressService",
	HandlerType: (*LessonProgressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLessonProgress",
			Handler:    _LessonProgressService_CreateLessonProgress_Handler,
		},
		{
			MethodName: "ReadLessonProgressByUserId",
			Handler:    _LessonProgressService_ReadLessonProgressByUserId_Handler,
		},
		{
			MethodName: "ReadLessonProgressByUserIdAndLessonId",
			Handler:    _LessonProgressService_ReadLessonProgressByUserIdAndLessonId_Handler,
		},
		{
			MethodName: "ReadModuleProgressByUserId",
			Handler:    _LessonProgressService_ReadModuleProgressByUserId_Handler,
		},
		{
			MethodName: "ReadModuleStatistics",
			Handler:    _LessonProgressService_ReadModuleStatistics_Handler,
		},
		{
			MethodName: "ReadCourseProgressByUserId",
			Handler:    _LessonProgressService_ReadCourseProgressByUserId_Handler,
		},
		{
			MethodName: "ReadCourseStatistics",
			Handler:    _LessonProgressService_ReadCourseStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lesson_progress_service.proto",
}
