// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/completed_module_service.proto

package completedmoduleservicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompletedModule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ModuleId      string                 `protobuf:"bytes,2,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletedModule) Reset() {
	*x = CompletedModule{}
	mi := &file_proto_completed_module_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletedModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletedModule) ProtoMessage() {}

func (x *CompletedModule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_module_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletedModule.ProtoReflect.Descriptor instead.
func (*CompletedModule) Descriptor() ([]byte, []int) {
	return file_proto_completed_module_service_proto_rawDescGZIP(), []int{0}
}

func (x *CompletedModule) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CompletedModule) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

type CreateCompletedModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ModuleId      string                 `protobuf:"bytes,2,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompletedModuleRequest) Reset() {
	*x = CreateCompletedModuleRequest{}
	mi := &file_proto_completed_module_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompletedModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompletedModuleRequest) ProtoMessage() {}

func (x *CreateCompletedModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_module_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompletedModuleRequest.ProtoReflect.Descriptor instead.
func (*CreateCompletedModuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_completed_module_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCompletedModuleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCompletedModuleRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

type CreateCompletedModuleResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CompletedModule *CompletedModule       `protobuf:"bytes,1,opt,name=completed_module,json=completedModule,proto3" json:"completed_module,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateCompletedModuleResponse) Reset() {
	*x = CreateCompletedModuleResponse{}
	mi := &file_proto_completed_module_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompletedModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompletedModuleResponse) ProtoMessage() {}

func (x *CreateCompletedModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_module_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompletedModuleResponse.ProtoReflect.Descriptor instead.
func (*CreateCompletedModuleResponse) Descriptor() ([]byte, []int) {
	return file_proto_completed_module_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCompletedModuleResponse) GetCompletedModule() *CompletedModule {
	if x != nil {
		return x.CompletedModule
	}
	return nil
}

type ReadCompletedModuleByUserIdAndModuleIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ModuleId      string                 `protobuf:"bytes,2,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCompletedModuleByUserIdAndModuleIdRequest) Reset() {
	*x = ReadCompletedModuleByUserIdAndModuleIdRequest{}
	mi := &file_proto_completed_module_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCompletedModuleByUserIdAndModuleIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCompletedModuleByUserIdAndModuleIdRequest) ProtoMessage() {}

func (x *ReadCompletedModuleByUserIdAndModuleIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_module_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCompletedModuleByUserIdAndModuleIdRequest.ProtoReflect.Descriptor instead.
func (*ReadCompletedModuleByUserIdAndModuleIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_completed_module_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReadCompletedModuleByUserIdAndModuleIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReadCompletedModuleByUserIdAndModuleIdRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

type ReadCompletedModuleByUserIdAndModuleIdResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CompletedModule *CompletedModule       `protobuf:"bytes,1,opt,name=completed_module,json=completedModule,proto3" json:"completed_module,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReadCompletedModuleByUserIdAndModuleIdResponse) Reset() {
	*x = ReadCompletedModuleByUserIdAndModuleIdResponse{}
	mi := &file_proto_completed_module_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCompletedModuleByUserIdAndModuleIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCompletedModuleByUserIdAndModuleIdResponse) ProtoMessage() {}

func (x *ReadCompletedModuleByUserIdAndModuleIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_module_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCompletedModuleByUserIdAndModuleIdResponse.ProtoReflect.Descriptor instead.
func (*ReadCompletedModuleByUserIdAndModuleIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_completed_module_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReadCompletedModuleByUserIdAndModuleIdResponse) GetCompletedModule() *CompletedModule {
	if x != nil {
		return x.CompletedModule
	}
	return nil
}

type ReadAllCompletedModulesByModuleIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllCompletedModulesByModuleIdRequest) Reset() {
	*x = ReadAllCompletedModulesByModuleIdRequest{}
	mi := &file_proto_completed_module_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCompletedModulesByModuleIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCompletedModulesByModuleIdRequest) ProtoMessage() {}

func (x *ReadAllCompletedModulesByModuleIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_module_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCompletedModulesByModuleIdRequest.ProtoReflect.Descriptor instead.
func (*ReadAllCompletedModulesByModuleIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_completed_module_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReadAllCompletedModulesByModuleIdRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

type ReadAllCompletedModulesByModuleIdResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CompletedModules []*CompletedModule     `protobuf:"bytes,1,rep,name=completed_modules,json=completedModules,proto3" json:"completed_modules,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReadAllCompletedModulesByModuleIdResponse) Reset() {
	*x = ReadAllCompletedModulesByModuleIdResponse{}
	mi := &file_proto_completed_module_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCompletedModulesByModuleIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCompletedModulesByModuleIdResponse) ProtoMessage() {}

func (x *ReadAllCompletedModulesByModuleIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_module_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCompletedModulesByModuleIdResponse.ProtoReflect.Descriptor instead.
func (*ReadAllCompletedModulesByModuleIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_completed_module_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReadAllCompletedModulesByModuleIdResponse) GetCompletedModules() []*CompletedModule {
	if x != nil {
		return x.CompletedModules
	}
	return nil
}

type ReadAllCompletedModulesByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllCompletedModulesByUserIdRequest) Reset() {
	*x = ReadAllCompletedModulesByUserIdRequest{}
	mi := &file_proto_completed_module_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCompletedModulesByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCompletedModulesByUserIdRequest) ProtoMessage() {}

func (x *ReadAllCompletedModulesByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_module_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCompletedModulesByUserIdRequest.ProtoReflect.Descriptor instead.
func (*ReadAllCompletedModulesByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_completed_module_service_proto_rawDescGZIP(), []int{7}
}

func (x *ReadAllCompletedModulesByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ReadAllCompletedModulesByUserIdResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CompletedModules []*CompletedModule     `protobuf:"bytes,1,rep,name=completed_modules,json=completedModules,proto3" json:"completed_modules,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReadAllCompletedModulesByUserIdResponse) Reset() {
	*x = ReadAllCompletedModulesByUserIdResponse{}
	mi := &file_proto_completed_module_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCompletedModulesByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCompletedModulesByUserIdResponse) ProtoMessage() {}

func (x *ReadAllCompletedModulesByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_completed_module_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCompletedModulesByUserIdResponse.ProtoReflect.Descriptor instead.
func (*ReadAllCompletedModulesByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_completed_module_service_proto_rawDescGZIP(), []int{8}
}

func (x *ReadAllCompletedModulesByUserIdResponse) GetCompletedModules() []*CompletedModule {
	if x != nil {
		return x.CompletedModules
	}
	return nil
}

var File_proto_completed_module_service_proto protoreflect.FileDescriptor

const file_proto_completed_module_service_proto_rawDesc = "" +
	"\n" +
	"$proto/completed_module_service.proto\x12\x16completedmoduleservice\"G\n" +
	"\x0fCompletedModule\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tmodule_id\x18\x02 \x01(\tR\bmoduleId\"T\n" +
	"\x1cCreateCompletedModuleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tmodule_id\x18\x02 \x01(\tR\bmoduleId\"s\n" +
	"\x1dCreateCompletedModuleResponse\x12R\n" +
	"\x10completed_module\x18\x01 \x01(\v2'.completedmoduleservice.CompletedModuleR\x0fcompletedModule\"e\n" +
	"-ReadCompletedModuleByUserIdAndModuleIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tmodule_id\x18\x02 \x01(\tR\bmoduleId\"\x84\x01\n" +
	".ReadCompletedModuleByUserIdAndModuleIdResponse\x12R\n" +
	"\x10completed_module\x18\x01 \x01(\v2'.completedmoduleservice.CompletedModuleR\x0fcompletedModule\"G\n" +
	"(ReadAllCompletedModulesByModuleIdRequest\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\"\x81\x01\n" +
	")ReadAllCompletedModulesByModuleIdResponse\x12T\n" +
	"\x11completed_modules\x18\x01 \x03(\v2'.completedmoduleservice.CompletedModuleR\x10completedModules\"A\n" +
	"&ReadAllCompletedModulesByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x7f\n" +
	"'ReadAllCompletedModulesByUserIdResponse\x12T\n" +
	"\x11completed_modules\x18\x01 \x03(\v2'.completedmoduleservice.CompletedModuleR\x10completedModules2\xa9\x05\n" +
	"\x16CompletedModuleService\x12\x84\x01\n" +
	"\x15CreateCompletedModule\x124.completedmoduleservice.CreateCompletedModuleRequest\x1a5.completedmoduleservice.CreateCompletedModuleResponse\x12\xb7\x01\n" +
	"&ReadCompletedModuleByUserIdAndModuleId\x12E.completedmoduleservice.ReadCompletedModuleByUserIdAndModuleIdRequest\x1aF.completedmoduleservice.ReadCompletedModuleByUserIdAndModuleIdResponse\x12\xa8\x01\n" +
	"!ReadAllCompletedModulesByModuleId\x12@.completedmoduleservice.ReadAllCompletedModulesByModuleIdRequest\x1aA.completedmoduleservice.ReadAllCompletedModulesByModuleIdResponse\x12\xa2\x01\n" +
	"\x1fReadAllCompletedModulesByUserId\x12>.completedmoduleservice.ReadAllCompletedModulesByUserIdRequest\x1a?.completedmoduleservice.ReadAllCompletedModulesByUserIdResponseB Z\x1eproto/completedmoduleservicepbb\x06proto3"

var (
	file_proto_completed_module_service_proto_rawDescOnce sync.Once
	file_proto_completed_module_service_proto_rawDescData []byte
)

func file_proto_completed_module_service_proto_rawDescGZIP() []byte {
	file_proto_completed_module_service_proto_rawDescOnce.Do(func() {
		file_proto_completed_module_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_completed_module_service_proto_rawDesc), len(file_proto_completed_module_service_proto_rawDesc)))
	})
	return file_proto_completed_module_service_proto_rawDescData
}

var file_proto_completed_module_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_completed_module_service_proto_goTypes = []any{
	(*CompletedModule)(nil),                                // 0: completedmoduleservice.CompletedModule
	(*CreateCompletedModuleRequest)(nil),                   // 1: completedmoduleservice.CreateCompletedModuleRequest
	(*CreateCompletedModuleResponse)(nil),                  // 2: completedmoduleservice.CreateCompletedModuleResponse
	(*ReadCompletedModuleByUserIdAndModuleIdRequest)(nil),  // 3: completedmoduleservice.ReadCompletedModuleByUserIdAndModuleIdRequest
	(*ReadCompletedModuleByUserIdAndModuleIdResponse)(nil), // 4: completedmoduleservice.ReadCompletedModuleByUserIdAndModuleIdResponse
	(*ReadAllCompletedModulesByModuleIdRequest)(nil),       // 5: completedmoduleservice.ReadAllCompletedModulesByModuleIdRequest
	(*ReadAllCompletedModulesByModuleIdResponse)(nil),      // 6: completedmoduleservice.ReadAllCompletedModulesByModuleIdResponse
	(*ReadAllCompletedModulesByUserIdRequest)(nil),         // 7: completedmoduleservice.ReadAllCompletedModulesByUserIdRequest
	(*ReadAllCompletedModulesByUserIdResponse)(nil),        // 8: completedmoduleservice.ReadAllCompletedModulesByUserIdResponse
}
var file_proto_completed_module_service_proto_depIdxs = []int32{
	0, // 0: completedmoduleservice.CreateCompletedModuleResponse.completed_module:type_name -> completedmoduleservice.CompletedModule
	0, // 1: completedmoduleservice.ReadCompletedModuleByUserIdAndModuleIdResponse.completed_module:type_name -> completedmoduleservice.CompletedModule
	0, // 2: completedmoduleservice.ReadAllCompletedModulesByModuleIdResponse.completed_modules:type_name -> completedmoduleservice.CompletedModule
	0, // 3: completedmoduleservice.ReadAllCompletedModulesByUserIdResponse.completed_modules:type_name -> completedmoduleservice.CompletedModule
	1, // 4: completedmoduleservice.CompletedModuleService.CreateCompletedModule:input_type -> completedmoduleservice.CreateCompletedModuleRequest
	3, // 5: completedmoduleservice.CompletedModuleService.ReadCompletedModuleByUserIdAndModuleId:input_type -> completedmoduleservice.ReadCompletedModuleByUserIdAndModuleIdRequest
	5, // 6: completedmoduleservice.CompletedModuleService.ReadAllCompletedModulesByModuleId:input_type -> completedmoduleservice.ReadAllCompletedModulesByModuleIdRequest
	7, // 7: completedmoduleservice.CompletedModuleService.ReadAllCompletedModulesByUserId:input_type -> completedmoduleservice.ReadAllCompletedModulesByUserIdRequest
	2, // 8: completedmoduleservice.CompletedModuleService.CreateCompletedModule:output_type -> completedmoduleservice.CreateCompletedModuleResponse
	4, // 9: completedmoduleservice.CompletedModuleService.ReadCompletedModuleByUserIdAndModuleId:output_type -> completedmoduleservice.ReadCompletedModuleByUserIdAndModuleIdResponse
	6, // 10: completedmoduleservice.CompletedModuleService.ReadAllCompletedModulesByModuleId:output_type -> completedmoduleservice.ReadAllCompletedModulesByModuleIdResponse
	8, // 11: completedmoduleservice.CompletedModuleService.ReadAllCompletedModulesByUserId:output_type -> completedmoduleservice.ReadAllCompletedModulesByUserIdResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_completed_module_service_proto_init() }
func file_proto_completed_module_service_proto_init() {
	if File_proto_completed_module_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_completed_module_service_proto_rawDesc), len(file_proto_completed_module_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_completed_module_service_proto_goTypes,
		DependencyIndexes: file_proto_completed_module_service_proto_depIdxs,
		MessageInfos:      file_proto_completed_module_service_proto_msgTypes,
	}.Build()
	File_proto_completed_module_service_proto = out.File
	file_proto_completed_module_service_proto_goTypes = nil
	file_proto_completed_module_service_proto_depIdxs = nil
}
