// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: proto/completed_module_service.proto

package completedmoduleservicepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CompletedModuleService_CreateCompletedModule_FullMethodName                  = "/completedmoduleservice.CompletedModuleService/CreateCompletedModule"
	CompletedModuleService_ReadCompletedModuleByUserIdAndModuleId_FullMethodName = "/completedmoduleservice.CompletedModuleService/ReadCompletedModuleByUserIdAndModuleId"
	CompletedModuleService_ReadAllCompletedModulesByModuleId_FullMethodName      = "/completedmoduleservice.CompletedModuleService/ReadAllCompletedModulesByModuleId"
	CompletedModuleService_ReadAllCompletedModulesByUserId_FullMethodName        = "/completedmoduleservice.CompletedModuleService/ReadAllCompletedModulesByUserId"
)

// CompletedModuleServiceClient is the client API for CompletedModuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompletedModuleServiceClient interface {
	CreateCompletedModule(ctx context.Context, in *CreateCompletedModuleRequest, opts ...grpc.CallOption) (*CreateCompletedModuleResponse, error)
	ReadCompletedModuleByUserIdAndModuleId(ctx context.Context, in *ReadCompletedModuleByUserIdAndModuleIdRequest, opts ...grpc.CallOption) (*ReadCompletedModuleByUserIdAndModuleIdResponse, error)
	ReadAllCompletedModulesByModuleId(ctx context.Context, in *ReadAllCompletedModulesByModuleIdRequest, opts ...grpc.CallOption) (*ReadAllCompletedModulesByModuleIdResponse, error)
	ReadAllCompletedModulesByUserId(ctx context.Context, in *ReadAllCompletedModulesByUserIdRequest, opts ...grpc.CallOption) (*ReadAllCompletedModulesByUserIdResponse, error)
}

type completedModuleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCompletedModuleServiceClient(cc grpc.ClientConnInterface) CompletedModuleServiceClient {
	return &completedModuleServiceClient{cc}
}

func (c *completedModuleServiceClient) CreateCompletedModule(ctx context.Context, in *CreateCompletedModuleRequest, opts ...grpc.CallOption) (*CreateCompletedModuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCompletedModuleResponse)
	err := c.cc.Invoke(ctx, CompletedModuleService_CreateCompletedModule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *completedModuleServiceClient) ReadCompletedModuleByUserIdAndModuleId(ctx context.Context, in *ReadCompletedModuleByUserIdAndModuleIdRequest, opts ...grpc.CallOption) (*ReadCompletedModuleByUserIdAndModuleIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadCompletedModuleByUserIdAndModuleIdResponse)
	err := c.cc.Invoke(ctx, CompletedModuleService_ReadCompletedModuleByUserIdAndModuleId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *completedModuleServiceClient) ReadAllCompletedModulesByModuleId(ctx context.Context, in *ReadAllCompletedModulesByModuleIdRequest, opts ...grpc.CallOption) (*ReadAllCompletedModulesByModuleIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadAllCompletedModulesByModuleIdResponse)
	err := c.cc.Invoke(ctx, CompletedModuleService_ReadAllCompletedModulesByModuleId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *completedModuleServiceClient) ReadAllCompletedModulesByUserId(ctx context.Context, in *ReadAllCompletedModulesByUserIdRequest, opts ...grpc.CallOption) (*ReadAllCompletedModulesByUserIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadAllCompletedModulesByUserIdResponse)
	err := c.cc.Invoke(ctx, CompletedModuleService_ReadAllCompletedModulesByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompletedModuleServiceServer is the server API for CompletedModuleService service.
// All implementations must embed UnimplementedCompletedModuleServiceServer
// for forward compatibility.
type CompletedModuleServiceServer interface {
	CreateCompletedModule(context.Context, *CreateCompletedModuleRequest) (*CreateCompletedModuleResponse, error)
	ReadCompletedModuleByUserIdAndModuleId(context.Context, *ReadCompletedModuleByUserIdAndModuleIdRequest) (*ReadCompletedModuleByUserIdAndModuleIdResponse, error)
	ReadAllCompletedModulesByModuleId(context.Context, *ReadAllCompletedModulesByModuleIdRequest) (*ReadAllCompletedModulesByModuleIdResponse, error)
	ReadAllCompletedModulesByUserId(context.Context, *ReadAllCompletedModulesByUserIdRequest) (*ReadAllCompletedModulesByUserIdResponse, error)
	mustEmbedUnimplementedCompletedModuleServiceServer()
}

// UnimplementedCompletedModuleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompletedModuleServiceServer struct{}

func (UnimplementedCompletedModuleServiceServer) CreateCompletedModule(context.Context, *CreateCompletedModuleRequest) (*CreateCompletedModuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCompletedModule not implemented")
}
func (UnimplementedCompletedModuleServiceServer) ReadCompletedModuleByUserIdAndModuleId(context.Context, *ReadCompletedModuleByUserIdAndModuleIdRequest) (*ReadCompletedModuleByUserIdAndModuleIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadCompletedModuleByUserIdAndModuleId not implemented")
}
func (UnimplementedCompletedModuleServiceServer) ReadAllCompletedModulesByModuleId(context.Context, *ReadAllCompletedModulesByModuleIdRequest) (*ReadAllCompletedModulesByModuleIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadAllCompletedModulesByModuleId not implemented")
}
func (UnimplementedCompletedModuleServiceServer) ReadAllCompletedModulesByUserId(context.Context, *ReadAllCompletedModulesByUserIdRequest) (*ReadAllCompletedModulesByUserIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadAllCompletedModulesByUserId not implemented")
}
func (UnimplementedCompletedModuleServiceServer) mustEmbedUnimplementedCompletedModuleServiceServer() {
}
func (UnimplementedCompletedModuleServiceServer) testEmbeddedByValue() {}

// UnsafeCompletedModuleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompletedModuleServiceServer will
// result in compilation errors.
type UnsafeCompletedModuleServiceServer interface {
	mustEmbedUnimplementedCompletedModuleServiceServer()
}

func RegisterCompletedModuleServiceServer(s grpc.ServiceRegistrar, srv CompletedModuleServiceServer) {
	// If the following call panics, it indicates UnimplementedCompletedModuleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CompletedModuleService_ServiceDesc, srv)
}

func _CompletedModuleService_CreateCompletedModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompletedModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompletedModuleServiceServer).CreateCompletedModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompletedModuleService_CreateCompletedModule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompletedModuleServiceServer).CreateCompletedModule(ctx, req.(*CreateCompletedModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompletedModuleService_ReadCompletedModuleByUserIdAndModuleId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadCompletedModuleByUserIdAndModuleIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompletedModuleServiceServer).ReadCompletedModuleByUserIdAndModuleId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompletedModuleService_ReadCompletedModuleByUserIdAndModuleId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompletedModuleServiceServer).ReadCompletedModuleByUserIdAndModuleId(ctx, req.(*ReadCompletedModuleByUserIdAndModuleIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompletedModuleService_ReadAllCompletedModulesByModuleId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllCompletedModulesByModuleIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompletedModuleServiceServer).ReadAllCompletedModulesByModuleId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompletedModuleService_ReadAllCompletedModulesByModuleId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompletedModuleServiceServer).ReadAllCompletedModulesByModuleId(ctx, req.(*ReadAllCompletedModulesByModuleIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompletedModuleService_ReadAllCompletedModulesByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllCompletedModulesByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompletedModuleServiceServer).ReadAllCompletedModulesByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompletedModuleService_ReadAllCompletedModulesByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompletedModuleServiceServer).ReadAllCompletedModulesByUserId(ctx, req.(*ReadAllCompletedModulesByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CompletedModuleService_ServiceDesc is the grpc.ServiceDesc for CompletedModuleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CompletedModuleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "completedmoduleservice.CompletedModuleService",
	HandlerType: (*CompletedModuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCompletedModule",
			Handler:    _CompletedModuleService_CreateCompletedModule_Handler,
		},
		{
			MethodName: "ReadCompletedModuleByUserIdAndModuleId",
			Handler:    _CompletedModuleService_ReadCompletedModuleByUserIdAndModuleId_Handler,
		},
		{
			MethodName: "ReadAllCompletedModulesByModuleId",
			Handler:    _CompletedModuleService_ReadAllCompletedModulesByModuleId_Handler,
		},
		{
			MethodName: "ReadAllCompletedModulesByUserId",
			Handler:    _CompletedModuleService_ReadAllCompletedModulesByUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/completed_module_service.proto",
}
