// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: proto/lesson_service.proto

package lessonservicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lesson struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Position      int64                  `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`
	CourseId      string                 `protobuf:"bytes,6,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lesson) Reset() {
	*x = Lesson{}
	mi := &file_proto_lesson_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lesson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lesson) ProtoMessage() {}

func (x *Lesson) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lesson.ProtoReflect.Descriptor instead.
func (*Lesson) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{0}
}

func (x *Lesson) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lesson) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Lesson) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Lesson) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Lesson) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Lesson) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type CreateLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CourseId      string                 `protobuf:"bytes,4,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLessonRequest) Reset() {
	*x = CreateLessonRequest{}
	mi := &file_proto_lesson_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLessonRequest) ProtoMessage() {}

func (x *CreateLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLessonRequest.ProtoReflect.Descriptor instead.
func (*CreateLessonRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLessonRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLessonRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateLessonRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateLessonRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type CreateLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lesson        *Lesson                `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLessonResponse) Reset() {
	*x = CreateLessonResponse{}
	mi := &file_proto_lesson_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLessonResponse) ProtoMessage() {}

func (x *CreateLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLessonResponse.ProtoReflect.Descriptor instead.
func (*CreateLessonResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLessonResponse) GetLesson() *Lesson {
	if x != nil {
		return x.Lesson
	}
	return nil
}

type ReadLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadLessonRequest) Reset() {
	*x = ReadLessonRequest{}
	mi := &file_proto_lesson_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLessonRequest) ProtoMessage() {}

func (x *ReadLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLessonRequest.ProtoReflect.Descriptor instead.
func (*ReadLessonRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReadLessonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lesson        *Lesson                `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadLessonResponse) Reset() {
	*x = ReadLessonResponse{}
	mi := &file_proto_lesson_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLessonResponse) ProtoMessage() {}

func (x *ReadLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLessonResponse.ProtoReflect.Descriptor instead.
func (*ReadLessonResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReadLessonResponse) GetLesson() *Lesson {
	if x != nil {
		return x.Lesson
	}
	return nil
}

type ReadAllLessonsByModuleIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllLessonsByModuleIdRequest) Reset() {
	*x = ReadAllLessonsByModuleIdRequest{}
	mi := &file_proto_lesson_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllLessonsByModuleIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllLessonsByModuleIdRequest) ProtoMessage() {}

func (x *ReadAllLessonsByModuleIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllLessonsByModuleIdRequest.ProtoReflect.Descriptor instead.
func (*ReadAllLessonsByModuleIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReadAllLessonsByModuleIdRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

type ReadAllLessonsByModuleIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lessons       []*Lesson              `protobuf:"bytes,1,rep,name=lessons,proto3" json:"lessons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllLessonsByModuleIdResponse) Reset() {
	*x = ReadAllLessonsByModuleIdResponse{}
	mi := &file_proto_lesson_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllLessonsByModuleIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllLessonsByModuleIdResponse) ProtoMessage() {}

func (x *ReadAllLessonsByModuleIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllLessonsByModuleIdResponse.ProtoReflect.Descriptor instead.
func (*ReadAllLessonsByModuleIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReadAllLessonsByModuleIdResponse) GetLessons() []*Lesson {
	if x != nil {
		return x.Lessons
	}
	return nil
}

type UpdateLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Position      int64                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	CourseId      string                 `protobuf:"bytes,5,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLessonRequest) Reset() {
	*x = UpdateLessonRequest{}
	mi := &file_proto_lesson_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLessonRequest) ProtoMessage() {}

func (x *UpdateLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLessonRequest.ProtoReflect.Descriptor instead.
func (*UpdateLessonRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateLessonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLessonRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateLessonRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateLessonRequest) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *UpdateLessonRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type UpdateLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lesson        *Lesson                `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLessonResponse) Reset() {
	*x = UpdateLessonResponse{}
	mi := &file_proto_lesson_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLessonResponse) ProtoMessage() {}

func (x *UpdateLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLessonResponse.ProtoReflect.Descriptor instead.
func (*UpdateLessonResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateLessonResponse) GetLesson() *Lesson {
	if x != nil {
		return x.Lesson
	}
	return nil
}

type DeleteLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLessonRequest) Reset() {
	*x = DeleteLessonRequest{}
	mi := &file_proto_lesson_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLessonRequest) ProtoMessage() {}

func (x *DeleteLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLessonRequest.ProtoReflect.Descriptor instead.
func (*DeleteLessonRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteLessonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLessonResponse) Reset() {
	*x = DeleteLessonResponse{}
	mi := &file_proto_lesson_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLessonResponse) ProtoMessage() {}

func (x *DeleteLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLessonResponse.ProtoReflect.Descriptor instead.
func (*DeleteLessonResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_service_proto_rawDescGZIP(), []int{10}
}

var File_proto_lesson_service_proto protoreflect.FileDescriptor

const file_proto_lesson_service_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/lesson_service.proto\x12\rlessonservice\"\xa3\x01\n" +
	"\x06Lesson\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x03R\bposition\x12\x1b\n" +
	"\tcourse_id\x18\x06 \x01(\tR\bcourseId\"\x84\x01\n" +
	"\x13CreateLessonRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tcourse_id\x18\x04 \x01(\tR\bcourseId\"E\n" +
	"\x14CreateLessonResponse\x12-\n" +
	"\x06lesson\x18\x01 \x01(\v2\x15.lessonservice.LessonR\x06lesson\"#\n" +
	"\x11ReadLessonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x12ReadLessonResponse\x12-\n" +
	"\x06lesson\x18\x01 \x01(\v2\x15.lessonservice.LessonR\x06lesson\">\n" +
	"\x1fReadAllLessonsByModuleIdRequest\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\"S\n" +
	" ReadAllLessonsByModuleIdResponse\x12/\n" +
	"\alessons\x18\x01 \x03(\v2\x15.lessonservice.LessonR\alessons\"\x96\x01\n" +
	"\x13UpdateLessonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x03R\bposition\x12\x1b\n" +
	"\tcourse_id\x18\x05 \x01(\tR\bcourseId\"E\n" +
	"\x14UpdateLessonResponse\x12-\n" +
	"\x06lesson\x18\x01 \x01(\v2\x15.lessonservice.LessonR\x06lesson\"%\n" +
	"\x13DeleteLessonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteLessonResponse2\xea\x03\n" +
	"\rLessonService\x12W\n" +
	"\fCreateLesson\x12\".lessonservice.CreateLessonRequest\x1a#.lessonservice.CreateLessonResponse\x12Q\n" +
	"\n" +
	"ReadLesson\x12 .lessonservice.ReadLessonRequest\x1a!.lessonservice.ReadLessonResponse\x12{\n" +
	"\x18ReadAllLessonsByModuleId\x12..lessonservice.ReadAllLessonsByModuleIdRequest\x1a/.lessonservice.ReadAllLessonsByModuleIdResponse\x12W\n" +
	"\fUpdateLesson\x12\".lessonservice.UpdateLessonRequest\x1a#.lessonservice.UpdateLessonResponse\x12W\n" +
	"\fDeleteLesson\x12\".lessonservice.DeleteLessonRequest\x1a#.lessonservice.DeleteLessonResponseB\x17Z\x15proto/lessonservicepbb\x06proto3"

var (
	file_proto_lesson_service_proto_rawDescOnce sync.Once
	file_proto_lesson_service_proto_rawDescData []byte
)

func file_proto_lesson_service_proto_rawDescGZIP() []byte {
	file_proto_lesson_service_proto_rawDescOnce.Do(func() {
		file_proto_lesson_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lesson_service_proto_rawDesc), len(file_proto_lesson_service_proto_rawDesc)))
	})
	return file_proto_lesson_service_proto_rawDescData
}

var file_proto_lesson_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_lesson_service_proto_goTypes = []any{
	(*Lesson)(nil),                           // 0: lessonservice.Lesson
	(*CreateLessonRequest)(nil),              // 1: lessonservice.CreateLessonRequest
	(*CreateLessonResponse)(nil),             // 2: lessonservice.CreateLessonResponse
	(*ReadLessonRequest)(nil),                // 3: lessonservice.ReadLessonRequest
	(*ReadLessonResponse)(nil),               // 4: lessonservice.ReadLessonResponse
	(*ReadAllLessonsByModuleIdRequest)(nil),  // 5: lessonservice.ReadAllLessonsByModuleIdRequest
	(*ReadAllLessonsByModuleIdResponse)(nil), // 6: lessonservice.ReadAllLessonsByModuleIdResponse
	(*UpdateLessonRequest)(nil),              // 7: lessonservice.UpdateLessonRequest
	(*UpdateLessonResponse)(nil),             // 8: lessonservice.UpdateLessonResponse
	(*DeleteLessonRequest)(nil),              // 9: lessonservice.DeleteLessonRequest
	(*DeleteLessonResponse)(nil),             // 10: lessonservice.DeleteLessonResponse
}
var file_proto_lesson_service_proto_depIdxs = []int32{
	0,  // 0: lessonservice.CreateLessonResponse.lesson:type_name -> lessonservice.Lesson
	0,  // 1: lessonservice.ReadLessonResponse.lesson:type_name -> lessonservice.Lesson
	0,  // 2: lessonservice.ReadAllLessonsByModuleIdResponse.lessons:type_name -> lessonservice.Lesson
	0,  // 3: lessonservice.UpdateLessonResponse.lesson:type_name -> lessonservice.Lesson
	1,  // 4: lessonservice.LessonService.CreateLesson:input_type -> lessonservice.CreateLessonRequest
	3,  // 5: lessonservice.LessonService.ReadLesson:input_type -> lessonservice.ReadLessonRequest
	5,  // 6: lessonservice.LessonService.ReadAllLessonsByModuleId:input_type -> lessonservice.ReadAllLessonsByModuleIdRequest
	7,  // 7: lessonservice.LessonService.UpdateLesson:input_type -> lessonservice.UpdateLessonRequest
	9,  // 8: lessonservice.LessonService.DeleteLesson:input_type -> lessonservice.DeleteLessonRequest
	2,  // 9: lessonservice.LessonService.CreateLesson:output_type -> lessonservice.CreateLessonResponse
	4,  // 10: lessonservice.LessonService.ReadLesson:output_type -> lessonservice.ReadLessonResponse
	6,  // 11: lessonservice.LessonService.ReadAllLessonsByModuleId:output_type -> lessonservice.ReadAllLessonsByModuleIdResponse
	8,  // 12: lessonservice.LessonService.UpdateLesson:output_type -> lessonservice.UpdateLessonResponse
	10, // 13: lessonservice.LessonService.DeleteLesson:output_type -> lessonservice.DeleteLessonResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_lesson_service_proto_init() }
func file_proto_lesson_service_proto_init() {
	if File_proto_lesson_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lesson_service_proto_rawDesc), len(file_proto_lesson_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lesson_service_proto_goTypes,
		DependencyIndexes: file_proto_lesson_service_proto_depIdxs,
		MessageInfos:      file_proto_lesson_service_proto_msgTypes,
	}.Build()
	File_proto_lesson_service_proto = out.File
	file_proto_lesson_service_proto_goTypes = nil
	file_proto_lesson_service_proto_depIdxs = nil
}
